// Code generated by ent, DO NOT EDIT.

package internal

import "context"

// SchemaConfig represents alternative schema names for all tables
// that can be passed at runtime.
type SchemaConfig struct {
	ApiLog              string // ApiLog table.
	BankAccount         string // BankAccount table.
	Banner              string // Banner table.
	Comment             string // Comment table.
	Configuration       string // Configuration table.
	Currency            string // Currency table.
	DocumentType        string // DocumentType table.
	ExchangeRate        string // ExchangeRate table.
	Message             string // Message table.
	Notification        string // Notification table.
	PaymentCommitment   string // PaymentCommitment table.
	PaymentNotification string // PaymentNotification table.
	ResponseCode        string // ResponseCode table.
	ThirdPartyAccount   string // ThirdPartyAccount table.
	User                string // User table.
	UserDeviceToken     string // UserDeviceToken table.
	UserOtp             string // UserOtp table.
	UserPasswordHistory string // UserPasswordHistory table.
	UserSession         string // UserSession table.
	UserType            string // UserType table.
}

type schemaCtxKey struct{}

// SchemaConfigFromContext returns a SchemaConfig stored inside a context, or empty if there isn't one.
func SchemaConfigFromContext(ctx context.Context) SchemaConfig {
	config, _ := ctx.Value(schemaCtxKey{}).(SchemaConfig)
	return config
}

// NewSchemaConfigContext returns a new context with the given SchemaConfig attached.
func NewSchemaConfigContext(parent context.Context, config SchemaConfig) context.Context {
	return context.WithValue(parent, schemaCtxKey{}, config)
}
