// Code generated by ent, DO NOT EDIT.

package userotp

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/aaron/sakoo-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldEmail, v))
}

// OtpCode applies equality check predicate on the "otp_code" field. It's identical to OtpCodeEQ.
func OtpCode(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldOtpCode, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldAction, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldExpiresAt, v))
}

// Used applies equality check predicate on the "used" field. It's identical to UsedEQ.
func Used(v bool) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldUsed, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldCreatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldContainsFold(FieldEmail, v))
}

// OtpCodeEQ applies the EQ predicate on the "otp_code" field.
func OtpCodeEQ(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldOtpCode, v))
}

// OtpCodeNEQ applies the NEQ predicate on the "otp_code" field.
func OtpCodeNEQ(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNEQ(FieldOtpCode, v))
}

// OtpCodeIn applies the In predicate on the "otp_code" field.
func OtpCodeIn(vs ...string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldIn(FieldOtpCode, vs...))
}

// OtpCodeNotIn applies the NotIn predicate on the "otp_code" field.
func OtpCodeNotIn(vs ...string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNotIn(FieldOtpCode, vs...))
}

// OtpCodeGT applies the GT predicate on the "otp_code" field.
func OtpCodeGT(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGT(FieldOtpCode, v))
}

// OtpCodeGTE applies the GTE predicate on the "otp_code" field.
func OtpCodeGTE(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGTE(FieldOtpCode, v))
}

// OtpCodeLT applies the LT predicate on the "otp_code" field.
func OtpCodeLT(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLT(FieldOtpCode, v))
}

// OtpCodeLTE applies the LTE predicate on the "otp_code" field.
func OtpCodeLTE(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLTE(FieldOtpCode, v))
}

// OtpCodeContains applies the Contains predicate on the "otp_code" field.
func OtpCodeContains(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldContains(FieldOtpCode, v))
}

// OtpCodeHasPrefix applies the HasPrefix predicate on the "otp_code" field.
func OtpCodeHasPrefix(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldHasPrefix(FieldOtpCode, v))
}

// OtpCodeHasSuffix applies the HasSuffix predicate on the "otp_code" field.
func OtpCodeHasSuffix(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldHasSuffix(FieldOtpCode, v))
}

// OtpCodeEqualFold applies the EqualFold predicate on the "otp_code" field.
func OtpCodeEqualFold(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEqualFold(FieldOtpCode, v))
}

// OtpCodeContainsFold applies the ContainsFold predicate on the "otp_code" field.
func OtpCodeContainsFold(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldContainsFold(FieldOtpCode, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldContainsFold(FieldAction, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLTE(FieldExpiresAt, v))
}

// UsedEQ applies the EQ predicate on the "used" field.
func UsedEQ(v bool) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldUsed, v))
}

// UsedNEQ applies the NEQ predicate on the "used" field.
func UsedNEQ(v bool) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNEQ(FieldUsed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserOtp {
	return predicate.UserOtp(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserOtp) predicate.UserOtp {
	return predicate.UserOtp(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserOtp) predicate.UserOtp {
	return predicate.UserOtp(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserOtp) predicate.UserOtp {
	return predicate.UserOtp(sql.NotPredicates(p))
}
