// Code generated by ent, DO NOT EDIT.

package exchangerate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/aaron/sakoo-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldID, id))
}

// CurrencyID applies equality check predicate on the "currency_id" field. It's identical to CurrencyIDEQ.
func CurrencyID(v int64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldCurrencyID, v))
}

// RateFrom applies equality check predicate on the "rate_from" field. It's identical to RateFromEQ.
func RateFrom(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldRateFrom, v))
}

// RateTo applies equality check predicate on the "rate_to" field. It's identical to RateToEQ.
func RateTo(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldRateTo, v))
}

// RateAverage applies equality check predicate on the "rate_average" field. It's identical to RateAverageEQ.
func RateAverage(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldRateAverage, v))
}

// ValueDate applies equality check predicate on the "value_date" field. It's identical to ValueDateEQ.
func ValueDate(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldValueDate, v))
}

// NotifiedAt applies equality check predicate on the "notified_at" field. It's identical to NotifiedAtEQ.
func NotifiedAt(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldNotifiedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// CurrencyIDEQ applies the EQ predicate on the "currency_id" field.
func CurrencyIDEQ(v int64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldCurrencyID, v))
}

// CurrencyIDNEQ applies the NEQ predicate on the "currency_id" field.
func CurrencyIDNEQ(v int64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldCurrencyID, v))
}

// CurrencyIDIn applies the In predicate on the "currency_id" field.
func CurrencyIDIn(vs ...int64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldCurrencyID, vs...))
}

// CurrencyIDNotIn applies the NotIn predicate on the "currency_id" field.
func CurrencyIDNotIn(vs ...int64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldCurrencyID, vs...))
}

// CurrencyIDGT applies the GT predicate on the "currency_id" field.
func CurrencyIDGT(v int64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldCurrencyID, v))
}

// CurrencyIDGTE applies the GTE predicate on the "currency_id" field.
func CurrencyIDGTE(v int64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldCurrencyID, v))
}

// CurrencyIDLT applies the LT predicate on the "currency_id" field.
func CurrencyIDLT(v int64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldCurrencyID, v))
}

// CurrencyIDLTE applies the LTE predicate on the "currency_id" field.
func CurrencyIDLTE(v int64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldCurrencyID, v))
}

// RateFromEQ applies the EQ predicate on the "rate_from" field.
func RateFromEQ(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldRateFrom, v))
}

// RateFromNEQ applies the NEQ predicate on the "rate_from" field.
func RateFromNEQ(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldRateFrom, v))
}

// RateFromIn applies the In predicate on the "rate_from" field.
func RateFromIn(vs ...float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldRateFrom, vs...))
}

// RateFromNotIn applies the NotIn predicate on the "rate_from" field.
func RateFromNotIn(vs ...float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldRateFrom, vs...))
}

// RateFromGT applies the GT predicate on the "rate_from" field.
func RateFromGT(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldRateFrom, v))
}

// RateFromGTE applies the GTE predicate on the "rate_from" field.
func RateFromGTE(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldRateFrom, v))
}

// RateFromLT applies the LT predicate on the "rate_from" field.
func RateFromLT(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldRateFrom, v))
}

// RateFromLTE applies the LTE predicate on the "rate_from" field.
func RateFromLTE(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldRateFrom, v))
}

// RateToEQ applies the EQ predicate on the "rate_to" field.
func RateToEQ(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldRateTo, v))
}

// RateToNEQ applies the NEQ predicate on the "rate_to" field.
func RateToNEQ(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldRateTo, v))
}

// RateToIn applies the In predicate on the "rate_to" field.
func RateToIn(vs ...float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldRateTo, vs...))
}

// RateToNotIn applies the NotIn predicate on the "rate_to" field.
func RateToNotIn(vs ...float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldRateTo, vs...))
}

// RateToGT applies the GT predicate on the "rate_to" field.
func RateToGT(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldRateTo, v))
}

// RateToGTE applies the GTE predicate on the "rate_to" field.
func RateToGTE(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldRateTo, v))
}

// RateToLT applies the LT predicate on the "rate_to" field.
func RateToLT(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldRateTo, v))
}

// RateToLTE applies the LTE predicate on the "rate_to" field.
func RateToLTE(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldRateTo, v))
}

// RateAverageEQ applies the EQ predicate on the "rate_average" field.
func RateAverageEQ(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldRateAverage, v))
}

// RateAverageNEQ applies the NEQ predicate on the "rate_average" field.
func RateAverageNEQ(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldRateAverage, v))
}

// RateAverageIn applies the In predicate on the "rate_average" field.
func RateAverageIn(vs ...float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldRateAverage, vs...))
}

// RateAverageNotIn applies the NotIn predicate on the "rate_average" field.
func RateAverageNotIn(vs ...float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldRateAverage, vs...))
}

// RateAverageGT applies the GT predicate on the "rate_average" field.
func RateAverageGT(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldRateAverage, v))
}

// RateAverageGTE applies the GTE predicate on the "rate_average" field.
func RateAverageGTE(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldRateAverage, v))
}

// RateAverageLT applies the LT predicate on the "rate_average" field.
func RateAverageLT(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldRateAverage, v))
}

// RateAverageLTE applies the LTE predicate on the "rate_average" field.
func RateAverageLTE(v float64) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldRateAverage, v))
}

// ValueDateEQ applies the EQ predicate on the "value_date" field.
func ValueDateEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldValueDate, v))
}

// ValueDateNEQ applies the NEQ predicate on the "value_date" field.
func ValueDateNEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldValueDate, v))
}

// ValueDateIn applies the In predicate on the "value_date" field.
func ValueDateIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldValueDate, vs...))
}

// ValueDateNotIn applies the NotIn predicate on the "value_date" field.
func ValueDateNotIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldValueDate, vs...))
}

// ValueDateGT applies the GT predicate on the "value_date" field.
func ValueDateGT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldValueDate, v))
}

// ValueDateGTE applies the GTE predicate on the "value_date" field.
func ValueDateGTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldValueDate, v))
}

// ValueDateLT applies the LT predicate on the "value_date" field.
func ValueDateLT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldValueDate, v))
}

// ValueDateLTE applies the LTE predicate on the "value_date" field.
func ValueDateLTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldValueDate, v))
}

// NotifiedAtEQ applies the EQ predicate on the "notified_at" field.
func NotifiedAtEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldNotifiedAt, v))
}

// NotifiedAtNEQ applies the NEQ predicate on the "notified_at" field.
func NotifiedAtNEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldNotifiedAt, v))
}

// NotifiedAtIn applies the In predicate on the "notified_at" field.
func NotifiedAtIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldNotifiedAt, vs...))
}

// NotifiedAtNotIn applies the NotIn predicate on the "notified_at" field.
func NotifiedAtNotIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldNotifiedAt, vs...))
}

// NotifiedAtGT applies the GT predicate on the "notified_at" field.
func NotifiedAtGT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldNotifiedAt, v))
}

// NotifiedAtGTE applies the GTE predicate on the "notified_at" field.
func NotifiedAtGTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldNotifiedAt, v))
}

// NotifiedAtLT applies the LT predicate on the "notified_at" field.
func NotifiedAtLT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldNotifiedAt, v))
}

// NotifiedAtLTE applies the LTE predicate on the "notified_at" field.
func NotifiedAtLTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldNotifiedAt, v))
}

// NotifiedAtIsNil applies the IsNil predicate on the "notified_at" field.
func NotifiedAtIsNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIsNull(FieldNotifiedAt))
}

// NotifiedAtNotNil applies the NotNil predicate on the "notified_at" field.
func NotifiedAtNotNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotNull(FieldNotifiedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExchangeRate) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExchangeRate) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExchangeRate) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.NotPredicates(p))
}
