// Code generated by ent, DO NOT EDIT.

package bankaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/aaron/sakoo-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldUserID, v))
}

// BankName applies equality check predicate on the "bank_name" field. It's identical to BankNameEQ.
func BankName(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldBankName, v))
}

// AccountNumber applies equality check predicate on the "account_number" field. It's identical to AccountNumberEQ.
func AccountNumber(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldAccountNumber, v))
}

// AccountType applies equality check predicate on the "account_type" field. It's identical to AccountTypeEQ.
func AccountType(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldAccountType, v))
}

// HolderName applies equality check predicate on the "holder_name" field. It's identical to HolderNameEQ.
func HolderName(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldHolderName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldUserID, v))
}

// BankNameEQ applies the EQ predicate on the "bank_name" field.
func BankNameEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldBankName, v))
}

// BankNameNEQ applies the NEQ predicate on the "bank_name" field.
func BankNameNEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldBankName, v))
}

// BankNameIn applies the In predicate on the "bank_name" field.
func BankNameIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldBankName, vs...))
}

// BankNameNotIn applies the NotIn predicate on the "bank_name" field.
func BankNameNotIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldBankName, vs...))
}

// BankNameGT applies the GT predicate on the "bank_name" field.
func BankNameGT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldBankName, v))
}

// BankNameGTE applies the GTE predicate on the "bank_name" field.
func BankNameGTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldBankName, v))
}

// BankNameLT applies the LT predicate on the "bank_name" field.
func BankNameLT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldBankName, v))
}

// BankNameLTE applies the LTE predicate on the "bank_name" field.
func BankNameLTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldBankName, v))
}

// BankNameContains applies the Contains predicate on the "bank_name" field.
func BankNameContains(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContains(FieldBankName, v))
}

// BankNameHasPrefix applies the HasPrefix predicate on the "bank_name" field.
func BankNameHasPrefix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasPrefix(FieldBankName, v))
}

// BankNameHasSuffix applies the HasSuffix predicate on the "bank_name" field.
func BankNameHasSuffix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasSuffix(FieldBankName, v))
}

// BankNameEqualFold applies the EqualFold predicate on the "bank_name" field.
func BankNameEqualFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEqualFold(FieldBankName, v))
}

// BankNameContainsFold applies the ContainsFold predicate on the "bank_name" field.
func BankNameContainsFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContainsFold(FieldBankName, v))
}

// AccountNumberEQ applies the EQ predicate on the "account_number" field.
func AccountNumberEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldAccountNumber, v))
}

// AccountNumberNEQ applies the NEQ predicate on the "account_number" field.
func AccountNumberNEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldAccountNumber, v))
}

// AccountNumberIn applies the In predicate on the "account_number" field.
func AccountNumberIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldAccountNumber, vs...))
}

// AccountNumberNotIn applies the NotIn predicate on the "account_number" field.
func AccountNumberNotIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldAccountNumber, vs...))
}

// AccountNumberGT applies the GT predicate on the "account_number" field.
func AccountNumberGT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldAccountNumber, v))
}

// AccountNumberGTE applies the GTE predicate on the "account_number" field.
func AccountNumberGTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldAccountNumber, v))
}

// AccountNumberLT applies the LT predicate on the "account_number" field.
func AccountNumberLT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldAccountNumber, v))
}

// AccountNumberLTE applies the LTE predicate on the "account_number" field.
func AccountNumberLTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldAccountNumber, v))
}

// AccountNumberContains applies the Contains predicate on the "account_number" field.
func AccountNumberContains(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContains(FieldAccountNumber, v))
}

// AccountNumberHasPrefix applies the HasPrefix predicate on the "account_number" field.
func AccountNumberHasPrefix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasPrefix(FieldAccountNumber, v))
}

// AccountNumberHasSuffix applies the HasSuffix predicate on the "account_number" field.
func AccountNumberHasSuffix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasSuffix(FieldAccountNumber, v))
}

// AccountNumberEqualFold applies the EqualFold predicate on the "account_number" field.
func AccountNumberEqualFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEqualFold(FieldAccountNumber, v))
}

// AccountNumberContainsFold applies the ContainsFold predicate on the "account_number" field.
func AccountNumberContainsFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContainsFold(FieldAccountNumber, v))
}

// AccountTypeEQ applies the EQ predicate on the "account_type" field.
func AccountTypeEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldAccountType, v))
}

// AccountTypeNEQ applies the NEQ predicate on the "account_type" field.
func AccountTypeNEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldAccountType, v))
}

// AccountTypeIn applies the In predicate on the "account_type" field.
func AccountTypeIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldAccountType, vs...))
}

// AccountTypeNotIn applies the NotIn predicate on the "account_type" field.
func AccountTypeNotIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldAccountType, vs...))
}

// AccountTypeGT applies the GT predicate on the "account_type" field.
func AccountTypeGT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldAccountType, v))
}

// AccountTypeGTE applies the GTE predicate on the "account_type" field.
func AccountTypeGTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldAccountType, v))
}

// AccountTypeLT applies the LT predicate on the "account_type" field.
func AccountTypeLT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldAccountType, v))
}

// AccountTypeLTE applies the LTE predicate on the "account_type" field.
func AccountTypeLTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldAccountType, v))
}

// AccountTypeContains applies the Contains predicate on the "account_type" field.
func AccountTypeContains(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContains(FieldAccountType, v))
}

// AccountTypeHasPrefix applies the HasPrefix predicate on the "account_type" field.
func AccountTypeHasPrefix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasPrefix(FieldAccountType, v))
}

// AccountTypeHasSuffix applies the HasSuffix predicate on the "account_type" field.
func AccountTypeHasSuffix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasSuffix(FieldAccountType, v))
}

// AccountTypeEqualFold applies the EqualFold predicate on the "account_type" field.
func AccountTypeEqualFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEqualFold(FieldAccountType, v))
}

// AccountTypeContainsFold applies the ContainsFold predicate on the "account_type" field.
func AccountTypeContainsFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContainsFold(FieldAccountType, v))
}

// HolderNameEQ applies the EQ predicate on the "holder_name" field.
func HolderNameEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldHolderName, v))
}

// HolderNameNEQ applies the NEQ predicate on the "holder_name" field.
func HolderNameNEQ(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldHolderName, v))
}

// HolderNameIn applies the In predicate on the "holder_name" field.
func HolderNameIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldHolderName, vs...))
}

// HolderNameNotIn applies the NotIn predicate on the "holder_name" field.
func HolderNameNotIn(vs ...string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldHolderName, vs...))
}

// HolderNameGT applies the GT predicate on the "holder_name" field.
func HolderNameGT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldHolderName, v))
}

// HolderNameGTE applies the GTE predicate on the "holder_name" field.
func HolderNameGTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldHolderName, v))
}

// HolderNameLT applies the LT predicate on the "holder_name" field.
func HolderNameLT(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldHolderName, v))
}

// HolderNameLTE applies the LTE predicate on the "holder_name" field.
func HolderNameLTE(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldHolderName, v))
}

// HolderNameContains applies the Contains predicate on the "holder_name" field.
func HolderNameContains(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContains(FieldHolderName, v))
}

// HolderNameHasPrefix applies the HasPrefix predicate on the "holder_name" field.
func HolderNameHasPrefix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasPrefix(FieldHolderName, v))
}

// HolderNameHasSuffix applies the HasSuffix predicate on the "holder_name" field.
func HolderNameHasSuffix(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldHasSuffix(FieldHolderName, v))
}

// HolderNameEqualFold applies the EqualFold predicate on the "holder_name" field.
func HolderNameEqualFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEqualFold(FieldHolderName, v))
}

// HolderNameContainsFold applies the ContainsFold predicate on the "holder_name" field.
func HolderNameContainsFold(v string) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldContainsFold(FieldHolderName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BankAccount {
	return predicate.BankAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BankAccount) predicate.BankAccount {
	return predicate.BankAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BankAccount) predicate.BankAccount {
	return predicate.BankAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BankAccount) predicate.BankAccount {
	return predicate.BankAccount(sql.NotPredicates(p))
}
