// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/apilog"
	"github.com/aaron/sakoo-backend/ent/internal"
	"github.com/aaron/sakoo-backend/ent/predicate"
)

// ApiLogDelete is the builder for deleting a ApiLog entity.
type ApiLogDelete struct {
	config
	hooks    []Hook
	mutation *ApiLogMutation
}

// Where appends a list predicates to the ApiLogDelete builder.
func (_d *ApiLogDelete) Where(ps ...predicate.ApiLog) *ApiLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ApiLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ApiLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ApiLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(apilog.Table, sqlgraph.NewFieldSpec(apilog.FieldID, field.TypeInt))
	_spec.Node.Schema = _d.schemaConfig.ApiLog
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ApiLogDeleteOne is the builder for deleting a single ApiLog entity.
type ApiLogDeleteOne struct {
	_d *ApiLogDelete
}

// Where appends a list predicates to the ApiLogDelete builder.
func (_d *ApiLogDeleteOne) Where(ps ...predicate.ApiLog) *ApiLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ApiLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apilog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ApiLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
