// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aaron/sakoo-backend/ent/apilog"
)

// ApiLog is the model entity for the ApiLog schema.
type ApiLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TrackCode holds the value of the "track_code" field.
	TrackCode string `json:"track_code,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// HTTPStatus holds the value of the "http_status" field.
	HTTPStatus int `json:"http_status,omitempty"`
	// ResponseCode holds the value of the "response_code" field.
	ResponseCode string `json:"response_code,omitempty"`
	// LatencyMs holds the value of the "latency_ms" field.
	LatencyMs int64 `json:"latency_ms,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApiLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apilog.FieldID, apilog.FieldUserID, apilog.FieldHTTPStatus, apilog.FieldLatencyMs:
			values[i] = new(sql.NullInt64)
		case apilog.FieldTrackCode, apilog.FieldMethod, apilog.FieldPath, apilog.FieldResponseCode:
			values[i] = new(sql.NullString)
		case apilog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApiLog fields.
func (_m *ApiLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apilog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case apilog.FieldTrackCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field track_code", values[i])
			} else if value.Valid {
				_m.TrackCode = value.String
			}
		case apilog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case apilog.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case apilog.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case apilog.FieldHTTPStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_status", values[i])
			} else if value.Valid {
				_m.HTTPStatus = int(value.Int64)
			}
		case apilog.FieldResponseCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_code", values[i])
			} else if value.Valid {
				_m.ResponseCode = value.String
			}
		case apilog.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				_m.LatencyMs = value.Int64
			}
		case apilog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApiLog.
// This includes values selected through modifiers, order, etc.
func (_m *ApiLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ApiLog.
// Note that you need to call ApiLog.Unwrap() before calling this method if this ApiLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ApiLog) Update() *ApiLogUpdateOne {
	return NewApiLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ApiLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ApiLog) Unwrap() *ApiLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApiLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ApiLog) String() string {
	var builder strings.Builder
	builder.WriteString("ApiLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("track_code=")
	builder.WriteString(_m.TrackCode)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("http_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.HTTPStatus))
	builder.WriteString(", ")
	builder.WriteString("response_code=")
	builder.WriteString(_m.ResponseCode)
	builder.WriteString(", ")
	builder.WriteString("latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatencyMs))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ApiLogs is a parsable slice of ApiLog.
type ApiLogs []*ApiLog
