// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/banner"
	"github.com/aaron/sakoo-backend/ent/internal"
	"github.com/aaron/sakoo-backend/ent/predicate"
)

// BannerUpdate is the builder for updating Banner entities.
type BannerUpdate struct {
	config
	hooks    []Hook
	mutation *BannerMutation
}

// Where appends a list predicates to the BannerUpdate builder.
func (_u *BannerUpdate) Where(ps ...predicate.Banner) *BannerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *BannerUpdate) SetImageURL(v string) *BannerUpdate {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *BannerUpdate) SetNillableImageURL(v *string) *BannerUpdate {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// SetLink sets the "link" field.
func (_u *BannerUpdate) SetLink(v string) *BannerUpdate {
	_u.mutation.SetLink(v)
	return _u
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_u *BannerUpdate) SetNillableLink(v *string) *BannerUpdate {
	if v != nil {
		_u.SetLink(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *BannerUpdate) SetIsActive(v bool) *BannerUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *BannerUpdate) SetNillableIsActive(v *bool) *BannerUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *BannerUpdate) SetDisplayOrder(v int) *BannerUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *BannerUpdate) SetNillableDisplayOrder(v *int) *BannerUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *BannerUpdate) AddDisplayOrder(v int) *BannerUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BannerUpdate) SetCreatedAt(v time.Time) *BannerUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BannerUpdate) SetNillableCreatedAt(v *time.Time) *BannerUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BannerUpdate) SetUpdatedAt(v time.Time) *BannerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BannerMutation object of the builder.
func (_u *BannerUpdate) Mutation() *BannerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BannerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BannerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BannerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BannerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BannerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := banner.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BannerUpdate) check() error {
	if v, ok := _u.mutation.ImageURL(); ok {
		if err := banner.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Banner.image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Link(); ok {
		if err := banner.LinkValidator(v); err != nil {
			return &ValidationError{Name: "link", err: fmt.Errorf(`ent: validator failed for field "Banner.link": %w`, err)}
		}
	}
	return nil
}

func (_u *BannerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(banner.Table, banner.Columns, sqlgraph.NewFieldSpec(banner.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(banner.FieldImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Link(); ok {
		_spec.SetField(banner.FieldLink, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(banner.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(banner.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(banner.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(banner.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(banner.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.Banner
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{banner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BannerUpdateOne is the builder for updating a single Banner entity.
type BannerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BannerMutation
}

// SetImageURL sets the "image_url" field.
func (_u *BannerUpdateOne) SetImageURL(v string) *BannerUpdateOne {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *BannerUpdateOne) SetNillableImageURL(v *string) *BannerUpdateOne {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// SetLink sets the "link" field.
func (_u *BannerUpdateOne) SetLink(v string) *BannerUpdateOne {
	_u.mutation.SetLink(v)
	return _u
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_u *BannerUpdateOne) SetNillableLink(v *string) *BannerUpdateOne {
	if v != nil {
		_u.SetLink(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *BannerUpdateOne) SetIsActive(v bool) *BannerUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *BannerUpdateOne) SetNillableIsActive(v *bool) *BannerUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *BannerUpdateOne) SetDisplayOrder(v int) *BannerUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *BannerUpdateOne) SetNillableDisplayOrder(v *int) *BannerUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *BannerUpdateOne) AddDisplayOrder(v int) *BannerUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BannerUpdateOne) SetCreatedAt(v time.Time) *BannerUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BannerUpdateOne) SetNillableCreatedAt(v *time.Time) *BannerUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BannerUpdateOne) SetUpdatedAt(v time.Time) *BannerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BannerMutation object of the builder.
func (_u *BannerUpdateOne) Mutation() *BannerMutation {
	return _u.mutation
}

// Where appends a list predicates to the BannerUpdate builder.
func (_u *BannerUpdateOne) Where(ps ...predicate.Banner) *BannerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BannerUpdateOne) Select(field string, fields ...string) *BannerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Banner entity.
func (_u *BannerUpdateOne) Save(ctx context.Context) (*Banner, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BannerUpdateOne) SaveX(ctx context.Context) *Banner {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BannerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BannerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BannerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := banner.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BannerUpdateOne) check() error {
	if v, ok := _u.mutation.ImageURL(); ok {
		if err := banner.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Banner.image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Link(); ok {
		if err := banner.LinkValidator(v); err != nil {
			return &ValidationError{Name: "link", err: fmt.Errorf(`ent: validator failed for field "Banner.link": %w`, err)}
		}
	}
	return nil
}

func (_u *BannerUpdateOne) sqlSave(ctx context.Context) (_node *Banner, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(banner.Table, banner.Columns, sqlgraph.NewFieldSpec(banner.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Banner.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, banner.FieldID)
		for _, f := range fields {
			if !banner.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != banner.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(banner.FieldImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Link(); ok {
		_spec.SetField(banner.FieldLink, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(banner.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(banner.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(banner.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(banner.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(banner.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.Banner
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Banner{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{banner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
