// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/configuration"
)

// ConfigurationCreate is the builder for creating a Configuration entity.
type ConfigurationCreate struct {
	config
	mutation *ConfigurationMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *ConfigurationCreate) SetKey(v string) *ConfigurationCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *ConfigurationCreate) SetPayload(v map[string]interface{}) *ConfigurationCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConfigurationCreate) SetCreatedAt(v time.Time) *ConfigurationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConfigurationCreate) SetNillableCreatedAt(v *time.Time) *ConfigurationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConfigurationCreate) SetUpdatedAt(v time.Time) *ConfigurationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConfigurationCreate) SetNillableUpdatedAt(v *time.Time) *ConfigurationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ConfigurationMutation object of the builder.
func (_c *ConfigurationCreate) Mutation() *ConfigurationMutation {
	return _c.mutation
}

// Save creates the Configuration in the database.
func (_c *ConfigurationCreate) Save(ctx context.Context) (*Configuration, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConfigurationCreate) SaveX(ctx context.Context) *Configuration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfigurationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfigurationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConfigurationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := configuration.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := configuration.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConfigurationCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Configuration.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := configuration.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Configuration.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "Configuration.payload"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Configuration.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Configuration.updated_at"`)}
	}
	return nil
}

func (_c *ConfigurationCreate) sqlSave(ctx context.Context) (*Configuration, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConfigurationCreate) createSpec() (*Configuration, *sqlgraph.CreateSpec) {
	var (
		_node = &Configuration{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(configuration.Table, sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.Configuration
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(configuration.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(configuration.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(configuration.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(configuration.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ConfigurationCreateBulk is the builder for creating many Configuration entities in bulk.
type ConfigurationCreateBulk struct {
	config
	err      error
	builders []*ConfigurationCreate
}

// Save creates the Configuration entities in the database.
func (_c *ConfigurationCreateBulk) Save(ctx context.Context) ([]*Configuration, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Configuration, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConfigurationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConfigurationCreateBulk) SaveX(ctx context.Context) []*Configuration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfigurationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfigurationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
