// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/documenttype"
	"github.com/aaron/sakoo-backend/ent/internal"
	"github.com/aaron/sakoo-backend/ent/predicate"
)

// DocumentTypeUpdate is the builder for updating DocumentType entities.
type DocumentTypeUpdate struct {
	config
	hooks    []Hook
	mutation *DocumentTypeMutation
}

// Where appends a list predicates to the DocumentTypeUpdate builder.
func (_u *DocumentTypeUpdate) Where(ps ...predicate.DocumentType) *DocumentTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *DocumentTypeUpdate) SetCode(v string) *DocumentTypeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DocumentTypeUpdate) SetNillableCode(v *string) *DocumentTypeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DocumentTypeUpdate) SetName(v string) *DocumentTypeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DocumentTypeUpdate) SetNillableName(v *string) *DocumentTypeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *DocumentTypeUpdate) SetDisplayOrder(v int) *DocumentTypeUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *DocumentTypeUpdate) SetNillableDisplayOrder(v *int) *DocumentTypeUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *DocumentTypeUpdate) AddDisplayOrder(v int) *DocumentTypeUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DocumentTypeUpdate) SetCreatedAt(v time.Time) *DocumentTypeUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DocumentTypeUpdate) SetNillableCreatedAt(v *time.Time) *DocumentTypeUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the DocumentTypeMutation object of the builder.
func (_u *DocumentTypeUpdate) Mutation() *DocumentTypeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentTypeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := documenttype.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DocumentType.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := documenttype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DocumentType.name": %w`, err)}
		}
	}
	return nil
}

func (_u *DocumentTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documenttype.Table, documenttype.Columns, sqlgraph.NewFieldSpec(documenttype.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(documenttype.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(documenttype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(documenttype.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(documenttype.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(documenttype.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.DocumentType
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documenttype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentTypeUpdateOne is the builder for updating a single DocumentType entity.
type DocumentTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DocumentTypeMutation
}

// SetCode sets the "code" field.
func (_u *DocumentTypeUpdateOne) SetCode(v string) *DocumentTypeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DocumentTypeUpdateOne) SetNillableCode(v *string) *DocumentTypeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DocumentTypeUpdateOne) SetName(v string) *DocumentTypeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DocumentTypeUpdateOne) SetNillableName(v *string) *DocumentTypeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *DocumentTypeUpdateOne) SetDisplayOrder(v int) *DocumentTypeUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *DocumentTypeUpdateOne) SetNillableDisplayOrder(v *int) *DocumentTypeUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *DocumentTypeUpdateOne) AddDisplayOrder(v int) *DocumentTypeUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DocumentTypeUpdateOne) SetCreatedAt(v time.Time) *DocumentTypeUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DocumentTypeUpdateOne) SetNillableCreatedAt(v *time.Time) *DocumentTypeUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the DocumentTypeMutation object of the builder.
func (_u *DocumentTypeUpdateOne) Mutation() *DocumentTypeMutation {
	return _u.mutation
}

// Where appends a list predicates to the DocumentTypeUpdate builder.
func (_u *DocumentTypeUpdateOne) Where(ps ...predicate.DocumentType) *DocumentTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentTypeUpdateOne) Select(field string, fields ...string) *DocumentTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DocumentType entity.
func (_u *DocumentTypeUpdateOne) Save(ctx context.Context) (*DocumentType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentTypeUpdateOne) SaveX(ctx context.Context) *DocumentType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentTypeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := documenttype.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DocumentType.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := documenttype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DocumentType.name": %w`, err)}
		}
	}
	return nil
}

func (_u *DocumentTypeUpdateOne) sqlSave(ctx context.Context) (_node *DocumentType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documenttype.Table, documenttype.Columns, sqlgraph.NewFieldSpec(documenttype.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DocumentType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, documenttype.FieldID)
		for _, f := range fields {
			if !documenttype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != documenttype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(documenttype.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(documenttype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(documenttype.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(documenttype.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(documenttype.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.DocumentType
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &DocumentType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documenttype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
