// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/exchangerate"
)

// ExchangeRateCreate is the builder for creating a ExchangeRate entity.
type ExchangeRateCreate struct {
	config
	mutation *ExchangeRateMutation
	hooks    []Hook
}

// SetCurrencyID sets the "currency_id" field.
func (_c *ExchangeRateCreate) SetCurrencyID(v int64) *ExchangeRateCreate {
	_c.mutation.SetCurrencyID(v)
	return _c
}

// SetRateFrom sets the "rate_from" field.
func (_c *ExchangeRateCreate) SetRateFrom(v float64) *ExchangeRateCreate {
	_c.mutation.SetRateFrom(v)
	return _c
}

// SetRateTo sets the "rate_to" field.
func (_c *ExchangeRateCreate) SetRateTo(v float64) *ExchangeRateCreate {
	_c.mutation.SetRateTo(v)
	return _c
}

// SetRateAverage sets the "rate_average" field.
func (_c *ExchangeRateCreate) SetRateAverage(v float64) *ExchangeRateCreate {
	_c.mutation.SetRateAverage(v)
	return _c
}

// SetValueDate sets the "value_date" field.
func (_c *ExchangeRateCreate) SetValueDate(v time.Time) *ExchangeRateCreate {
	_c.mutation.SetValueDate(v)
	return _c
}

// SetNotifiedAt sets the "notified_at" field.
func (_c *ExchangeRateCreate) SetNotifiedAt(v time.Time) *ExchangeRateCreate {
	_c.mutation.SetNotifiedAt(v)
	return _c
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableNotifiedAt(v *time.Time) *ExchangeRateCreate {
	if v != nil {
		_c.SetNotifiedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExchangeRateCreate) SetCreatedAt(v time.Time) *ExchangeRateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableCreatedAt(v *time.Time) *ExchangeRateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExchangeRateCreate) SetUpdatedAt(v time.Time) *ExchangeRateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableUpdatedAt(v *time.Time) *ExchangeRateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ExchangeRateMutation object of the builder.
func (_c *ExchangeRateCreate) Mutation() *ExchangeRateMutation {
	return _c.mutation
}

// Save creates the ExchangeRate in the database.
func (_c *ExchangeRateCreate) Save(ctx context.Context) (*ExchangeRate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExchangeRateCreate) SaveX(ctx context.Context) *ExchangeRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeRateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeRateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExchangeRateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := exchangerate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := exchangerate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExchangeRateCreate) check() error {
	if _, ok := _c.mutation.CurrencyID(); !ok {
		return &ValidationError{Name: "currency_id", err: errors.New(`ent: missing required field "ExchangeRate.currency_id"`)}
	}
	if _, ok := _c.mutation.RateFrom(); !ok {
		return &ValidationError{Name: "rate_from", err: errors.New(`ent: missing required field "ExchangeRate.rate_from"`)}
	}
	if _, ok := _c.mutation.RateTo(); !ok {
		return &ValidationError{Name: "rate_to", err: errors.New(`ent: missing required field "ExchangeRate.rate_to"`)}
	}
	if _, ok := _c.mutation.RateAverage(); !ok {
		return &ValidationError{Name: "rate_average", err: errors.New(`ent: missing required field "ExchangeRate.rate_average"`)}
	}
	if _, ok := _c.mutation.ValueDate(); !ok {
		return &ValidationError{Name: "value_date", err: errors.New(`ent: missing required field "ExchangeRate.value_date"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExchangeRate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ExchangeRate.updated_at"`)}
	}
	return nil
}

func (_c *ExchangeRateCreate) sqlSave(ctx context.Context) (*ExchangeRate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExchangeRateCreate) createSpec() (*ExchangeRate, *sqlgraph.CreateSpec) {
	var (
		_node = &ExchangeRate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exchangerate.Table, sqlgraph.NewFieldSpec(exchangerate.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.ExchangeRate
	if value, ok := _c.mutation.CurrencyID(); ok {
		_spec.SetField(exchangerate.FieldCurrencyID, field.TypeInt64, value)
		_node.CurrencyID = value
	}
	if value, ok := _c.mutation.RateFrom(); ok {
		_spec.SetField(exchangerate.FieldRateFrom, field.TypeFloat64, value)
		_node.RateFrom = value
	}
	if value, ok := _c.mutation.RateTo(); ok {
		_spec.SetField(exchangerate.FieldRateTo, field.TypeFloat64, value)
		_node.RateTo = value
	}
	if value, ok := _c.mutation.RateAverage(); ok {
		_spec.SetField(exchangerate.FieldRateAverage, field.TypeFloat64, value)
		_node.RateAverage = value
	}
	if value, ok := _c.mutation.ValueDate(); ok {
		_spec.SetField(exchangerate.FieldValueDate, field.TypeTime, value)
		_node.ValueDate = value
	}
	if value, ok := _c.mutation.NotifiedAt(); ok {
		_spec.SetField(exchangerate.FieldNotifiedAt, field.TypeTime, value)
		_node.NotifiedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(exchangerate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(exchangerate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ExchangeRateCreateBulk is the builder for creating many ExchangeRate entities in bulk.
type ExchangeRateCreateBulk struct {
	config
	err      error
	builders []*ExchangeRateCreate
}

// Save creates the ExchangeRate entities in the database.
func (_c *ExchangeRateCreateBulk) Save(ctx context.Context) ([]*ExchangeRate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExchangeRate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExchangeRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExchangeRateCreateBulk) SaveX(ctx context.Context) []*ExchangeRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeRateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeRateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
