// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aaron/sakoo-backend/ent/paymentnotification"
)

// PaymentNotification is the model entity for the PaymentNotification schema.
type PaymentNotification struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PaymentCommitmentID holds the value of the "payment_commitment_id" field.
	PaymentCommitmentID int64 `json:"payment_commitment_id,omitempty"`
	// AmountPaid holds the value of the "amount_paid" field.
	AmountPaid float64 `json:"amount_paid,omitempty"`
	// TransactionReference holds the value of the "transaction_reference" field.
	TransactionReference string `json:"transaction_reference,omitempty"`
	// NotificationDate holds the value of the "notification_date" field.
	NotificationDate time.Time `json:"notification_date,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentNotification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentnotification.FieldAmountPaid:
			values[i] = new(sql.NullFloat64)
		case paymentnotification.FieldID, paymentnotification.FieldPaymentCommitmentID:
			values[i] = new(sql.NullInt64)
		case paymentnotification.FieldTransactionReference:
			values[i] = new(sql.NullString)
		case paymentnotification.FieldNotificationDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentNotification fields.
func (_m *PaymentNotification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentnotification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case paymentnotification.FieldPaymentCommitmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_commitment_id", values[i])
			} else if value.Valid {
				_m.PaymentCommitmentID = value.Int64
			}
		case paymentnotification.FieldAmountPaid:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_paid", values[i])
			} else if value.Valid {
				_m.AmountPaid = value.Float64
			}
		case paymentnotification.FieldTransactionReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_reference", values[i])
			} else if value.Valid {
				_m.TransactionReference = value.String
			}
		case paymentnotification.FieldNotificationDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field notification_date", values[i])
			} else if value.Valid {
				_m.NotificationDate = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentNotification.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentNotification) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentNotification.
// Note that you need to call PaymentNotification.Unwrap() before calling this method if this PaymentNotification
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentNotification) Update() *PaymentNotificationUpdateOne {
	return NewPaymentNotificationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentNotification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentNotification) Unwrap() *PaymentNotification {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentNotification is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentNotification) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentNotification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("payment_commitment_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentCommitmentID))
	builder.WriteString(", ")
	builder.WriteString("amount_paid=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountPaid))
	builder.WriteString(", ")
	builder.WriteString("transaction_reference=")
	builder.WriteString(_m.TransactionReference)
	builder.WriteString(", ")
	builder.WriteString("notification_date=")
	builder.WriteString(_m.NotificationDate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentNotifications is a parsable slice of PaymentNotification.
type PaymentNotifications []*PaymentNotification
