// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/internal"
	"github.com/aaron/sakoo-backend/ent/paymentcommitment"
	"github.com/aaron/sakoo-backend/ent/predicate"
)

// PaymentCommitmentDelete is the builder for deleting a PaymentCommitment entity.
type PaymentCommitmentDelete struct {
	config
	hooks    []Hook
	mutation *PaymentCommitmentMutation
}

// Where appends a list predicates to the PaymentCommitmentDelete builder.
func (_d *PaymentCommitmentDelete) Where(ps ...predicate.PaymentCommitment) *PaymentCommitmentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PaymentCommitmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentCommitmentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PaymentCommitmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentcommitment.Table, sqlgraph.NewFieldSpec(paymentcommitment.FieldID, field.TypeInt))
	_spec.Node.Schema = _d.schemaConfig.PaymentCommitment
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PaymentCommitmentDeleteOne is the builder for deleting a single PaymentCommitment entity.
type PaymentCommitmentDeleteOne struct {
	_d *PaymentCommitmentDelete
}

// Where appends a list predicates to the PaymentCommitmentDelete builder.
func (_d *PaymentCommitmentDeleteOne) Where(ps ...predicate.PaymentCommitment) *PaymentCommitmentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PaymentCommitmentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentcommitment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentCommitmentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
