// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/internal"
	"github.com/aaron/sakoo-backend/ent/paymentnotification"
	"github.com/aaron/sakoo-backend/ent/predicate"
)

// PaymentNotificationUpdate is the builder for updating PaymentNotification entities.
type PaymentNotificationUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentNotificationMutation
}

// Where appends a list predicates to the PaymentNotificationUpdate builder.
func (_u *PaymentNotificationUpdate) Where(ps ...predicate.PaymentNotification) *PaymentNotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPaymentCommitmentID sets the "payment_commitment_id" field.
func (_u *PaymentNotificationUpdate) SetPaymentCommitmentID(v int64) *PaymentNotificationUpdate {
	_u.mutation.ResetPaymentCommitmentID()
	_u.mutation.SetPaymentCommitmentID(v)
	return _u
}

// SetNillablePaymentCommitmentID sets the "payment_commitment_id" field if the given value is not nil.
func (_u *PaymentNotificationUpdate) SetNillablePaymentCommitmentID(v *int64) *PaymentNotificationUpdate {
	if v != nil {
		_u.SetPaymentCommitmentID(*v)
	}
	return _u
}

// AddPaymentCommitmentID adds value to the "payment_commitment_id" field.
func (_u *PaymentNotificationUpdate) AddPaymentCommitmentID(v int64) *PaymentNotificationUpdate {
	_u.mutation.AddPaymentCommitmentID(v)
	return _u
}

// ClearPaymentCommitmentID clears the value of the "payment_commitment_id" field.
func (_u *PaymentNotificationUpdate) ClearPaymentCommitmentID() *PaymentNotificationUpdate {
	_u.mutation.ClearPaymentCommitmentID()
	return _u
}

// SetAmountPaid sets the "amount_paid" field.
func (_u *PaymentNotificationUpdate) SetAmountPaid(v float64) *PaymentNotificationUpdate {
	_u.mutation.ResetAmountPaid()
	_u.mutation.SetAmountPaid(v)
	return _u
}

// SetNillableAmountPaid sets the "amount_paid" field if the given value is not nil.
func (_u *PaymentNotificationUpdate) SetNillableAmountPaid(v *float64) *PaymentNotificationUpdate {
	if v != nil {
		_u.SetAmountPaid(*v)
	}
	return _u
}

// AddAmountPaid adds value to the "amount_paid" field.
func (_u *PaymentNotificationUpdate) AddAmountPaid(v float64) *PaymentNotificationUpdate {
	_u.mutation.AddAmountPaid(v)
	return _u
}

// SetTransactionReference sets the "transaction_reference" field.
func (_u *PaymentNotificationUpdate) SetTransactionReference(v string) *PaymentNotificationUpdate {
	_u.mutation.SetTransactionReference(v)
	return _u
}

// SetNillableTransactionReference sets the "transaction_reference" field if the given value is not nil.
func (_u *PaymentNotificationUpdate) SetNillableTransactionReference(v *string) *PaymentNotificationUpdate {
	if v != nil {
		_u.SetTransactionReference(*v)
	}
	return _u
}

// SetNotificationDate sets the "notification_date" field.
func (_u *PaymentNotificationUpdate) SetNotificationDate(v time.Time) *PaymentNotificationUpdate {
	_u.mutation.SetNotificationDate(v)
	return _u
}

// SetNillableNotificationDate sets the "notification_date" field if the given value is not nil.
func (_u *PaymentNotificationUpdate) SetNillableNotificationDate(v *time.Time) *PaymentNotificationUpdate {
	if v != nil {
		_u.SetNotificationDate(*v)
	}
	return _u
}

// Mutation returns the PaymentNotificationMutation object of the builder.
func (_u *PaymentNotificationUpdate) Mutation() *PaymentNotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentNotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentNotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentNotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentNotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentNotificationUpdate) check() error {
	if v, ok := _u.mutation.TransactionReference(); ok {
		if err := paymentnotification.TransactionReferenceValidator(v); err != nil {
			return &ValidationError{Name: "transaction_reference", err: fmt.Errorf(`ent: validator failed for field "PaymentNotification.transaction_reference": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentNotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentnotification.Table, paymentnotification.Columns, sqlgraph.NewFieldSpec(paymentnotification.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PaymentCommitmentID(); ok {
		_spec.SetField(paymentnotification.FieldPaymentCommitmentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentCommitmentID(); ok {
		_spec.AddField(paymentnotification.FieldPaymentCommitmentID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentCommitmentIDCleared() {
		_spec.ClearField(paymentnotification.FieldPaymentCommitmentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AmountPaid(); ok {
		_spec.SetField(paymentnotification.FieldAmountPaid, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountPaid(); ok {
		_spec.AddField(paymentnotification.FieldAmountPaid, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TransactionReference(); ok {
		_spec.SetField(paymentnotification.FieldTransactionReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.NotificationDate(); ok {
		_spec.SetField(paymentnotification.FieldNotificationDate, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.PaymentNotification
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentnotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentNotificationUpdateOne is the builder for updating a single PaymentNotification entity.
type PaymentNotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentNotificationMutation
}

// SetPaymentCommitmentID sets the "payment_commitment_id" field.
func (_u *PaymentNotificationUpdateOne) SetPaymentCommitmentID(v int64) *PaymentNotificationUpdateOne {
	_u.mutation.ResetPaymentCommitmentID()
	_u.mutation.SetPaymentCommitmentID(v)
	return _u
}

// SetNillablePaymentCommitmentID sets the "payment_commitment_id" field if the given value is not nil.
func (_u *PaymentNotificationUpdateOne) SetNillablePaymentCommitmentID(v *int64) *PaymentNotificationUpdateOne {
	if v != nil {
		_u.SetPaymentCommitmentID(*v)
	}
	return _u
}

// AddPaymentCommitmentID adds value to the "payment_commitment_id" field.
func (_u *PaymentNotificationUpdateOne) AddPaymentCommitmentID(v int64) *PaymentNotificationUpdateOne {
	_u.mutation.AddPaymentCommitmentID(v)
	return _u
}

// ClearPaymentCommitmentID clears the value of the "payment_commitment_id" field.
func (_u *PaymentNotificationUpdateOne) ClearPaymentCommitmentID() *PaymentNotificationUpdateOne {
	_u.mutation.ClearPaymentCommitmentID()
	return _u
}

// SetAmountPaid sets the "amount_paid" field.
func (_u *PaymentNotificationUpdateOne) SetAmountPaid(v float64) *PaymentNotificationUpdateOne {
	_u.mutation.ResetAmountPaid()
	_u.mutation.SetAmountPaid(v)
	return _u
}

// SetNillableAmountPaid sets the "amount_paid" field if the given value is not nil.
func (_u *PaymentNotificationUpdateOne) SetNillableAmountPaid(v *float64) *PaymentNotificationUpdateOne {
	if v != nil {
		_u.SetAmountPaid(*v)
	}
	return _u
}

// AddAmountPaid adds value to the "amount_paid" field.
func (_u *PaymentNotificationUpdateOne) AddAmountPaid(v float64) *PaymentNotificationUpdateOne {
	_u.mutation.AddAmountPaid(v)
	return _u
}

// SetTransactionReference sets the "transaction_reference" field.
func (_u *PaymentNotificationUpdateOne) SetTransactionReference(v string) *PaymentNotificationUpdateOne {
	_u.mutation.SetTransactionReference(v)
	return _u
}

// SetNillableTransactionReference sets the "transaction_reference" field if the given value is not nil.
func (_u *PaymentNotificationUpdateOne) SetNillableTransactionReference(v *string) *PaymentNotificationUpdateOne {
	if v != nil {
		_u.SetTransactionReference(*v)
	}
	return _u
}

// SetNotificationDate sets the "notification_date" field.
func (_u *PaymentNotificationUpdateOne) SetNotificationDate(v time.Time) *PaymentNotificationUpdateOne {
	_u.mutation.SetNotificationDate(v)
	return _u
}

// SetNillableNotificationDate sets the "notification_date" field if the given value is not nil.
func (_u *PaymentNotificationUpdateOne) SetNillableNotificationDate(v *time.Time) *PaymentNotificationUpdateOne {
	if v != nil {
		_u.SetNotificationDate(*v)
	}
	return _u
}

// Mutation returns the PaymentNotificationMutation object of the builder.
func (_u *PaymentNotificationUpdateOne) Mutation() *PaymentNotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentNotificationUpdate builder.
func (_u *PaymentNotificationUpdateOne) Where(ps ...predicate.PaymentNotification) *PaymentNotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentNotificationUpdateOne) Select(field string, fields ...string) *PaymentNotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentNotification entity.
func (_u *PaymentNotificationUpdateOne) Save(ctx context.Context) (*PaymentNotification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentNotificationUpdateOne) SaveX(ctx context.Context) *PaymentNotification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentNotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentNotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentNotificationUpdateOne) check() error {
	if v, ok := _u.mutation.TransactionReference(); ok {
		if err := paymentnotification.TransactionReferenceValidator(v); err != nil {
			return &ValidationError{Name: "transaction_reference", err: fmt.Errorf(`ent: validator failed for field "PaymentNotification.transaction_reference": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentNotificationUpdateOne) sqlSave(ctx context.Context) (_node *PaymentNotification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentnotification.Table, paymentnotification.Columns, sqlgraph.NewFieldSpec(paymentnotification.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentNotification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentnotification.FieldID)
		for _, f := range fields {
			if !paymentnotification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentnotification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PaymentCommitmentID(); ok {
		_spec.SetField(paymentnotification.FieldPaymentCommitmentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentCommitmentID(); ok {
		_spec.AddField(paymentnotification.FieldPaymentCommitmentID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentCommitmentIDCleared() {
		_spec.ClearField(paymentnotification.FieldPaymentCommitmentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AmountPaid(); ok {
		_spec.SetField(paymentnotification.FieldAmountPaid, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountPaid(); ok {
		_spec.AddField(paymentnotification.FieldAmountPaid, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TransactionReference(); ok {
		_spec.SetField(paymentnotification.FieldTransactionReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.NotificationDate(); ok {
		_spec.SetField(paymentnotification.FieldNotificationDate, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.PaymentNotification
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &PaymentNotification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentnotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
