// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/internal"
	"github.com/aaron/sakoo-backend/ent/predicate"
	"github.com/aaron/sakoo-backend/ent/responsecode"
)

// ResponseCodeUpdate is the builder for updating ResponseCode entities.
type ResponseCodeUpdate struct {
	config
	hooks    []Hook
	mutation *ResponseCodeMutation
}

// Where appends a list predicates to the ResponseCodeUpdate builder.
func (_u *ResponseCodeUpdate) Where(ps ...predicate.ResponseCode) *ResponseCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *ResponseCodeUpdate) SetCode(v string) *ResponseCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ResponseCodeUpdate) SetNillableCode(v *string) *ResponseCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetHTTPStatus sets the "http_status" field.
func (_u *ResponseCodeUpdate) SetHTTPStatus(v int) *ResponseCodeUpdate {
	_u.mutation.ResetHTTPStatus()
	_u.mutation.SetHTTPStatus(v)
	return _u
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_u *ResponseCodeUpdate) SetNillableHTTPStatus(v *int) *ResponseCodeUpdate {
	if v != nil {
		_u.SetHTTPStatus(*v)
	}
	return _u
}

// AddHTTPStatus adds value to the "http_status" field.
func (_u *ResponseCodeUpdate) AddHTTPStatus(v int) *ResponseCodeUpdate {
	_u.mutation.AddHTTPStatus(v)
	return _u
}

// SetDefaultMessage sets the "default_message" field.
func (_u *ResponseCodeUpdate) SetDefaultMessage(v string) *ResponseCodeUpdate {
	_u.mutation.SetDefaultMessage(v)
	return _u
}

// SetNillableDefaultMessage sets the "default_message" field if the given value is not nil.
func (_u *ResponseCodeUpdate) SetNillableDefaultMessage(v *string) *ResponseCodeUpdate {
	if v != nil {
		_u.SetDefaultMessage(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResponseCodeUpdate) SetDescription(v string) *ResponseCodeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResponseCodeUpdate) SetNillableDescription(v *string) *ResponseCodeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ResponseCodeUpdate) ClearDescription() *ResponseCodeUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the ResponseCodeMutation object of the builder.
func (_u *ResponseCodeUpdate) Mutation() *ResponseCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResponseCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResponseCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResponseCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResponseCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResponseCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := responsecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ResponseCode.code": %w`, err)}
		}
	}
	return nil
}

func (_u *ResponseCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(responsecode.Table, responsecode.Columns, sqlgraph.NewFieldSpec(responsecode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(responsecode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPStatus(); ok {
		_spec.SetField(responsecode.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(responsecode.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DefaultMessage(); ok {
		_spec.SetField(responsecode.FieldDefaultMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(responsecode.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(responsecode.FieldDescription, field.TypeString)
	}
	_spec.Node.Schema = _u.schemaConfig.ResponseCode
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{responsecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResponseCodeUpdateOne is the builder for updating a single ResponseCode entity.
type ResponseCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResponseCodeMutation
}

// SetCode sets the "code" field.
func (_u *ResponseCodeUpdateOne) SetCode(v string) *ResponseCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ResponseCodeUpdateOne) SetNillableCode(v *string) *ResponseCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetHTTPStatus sets the "http_status" field.
func (_u *ResponseCodeUpdateOne) SetHTTPStatus(v int) *ResponseCodeUpdateOne {
	_u.mutation.ResetHTTPStatus()
	_u.mutation.SetHTTPStatus(v)
	return _u
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_u *ResponseCodeUpdateOne) SetNillableHTTPStatus(v *int) *ResponseCodeUpdateOne {
	if v != nil {
		_u.SetHTTPStatus(*v)
	}
	return _u
}

// AddHTTPStatus adds value to the "http_status" field.
func (_u *ResponseCodeUpdateOne) AddHTTPStatus(v int) *ResponseCodeUpdateOne {
	_u.mutation.AddHTTPStatus(v)
	return _u
}

// SetDefaultMessage sets the "default_message" field.
func (_u *ResponseCodeUpdateOne) SetDefaultMessage(v string) *ResponseCodeUpdateOne {
	_u.mutation.SetDefaultMessage(v)
	return _u
}

// SetNillableDefaultMessage sets the "default_message" field if the given value is not nil.
func (_u *ResponseCodeUpdateOne) SetNillableDefaultMessage(v *string) *ResponseCodeUpdateOne {
	if v != nil {
		_u.SetDefaultMessage(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResponseCodeUpdateOne) SetDescription(v string) *ResponseCodeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResponseCodeUpdateOne) SetNillableDescription(v *string) *ResponseCodeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ResponseCodeUpdateOne) ClearDescription() *ResponseCodeUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the ResponseCodeMutation object of the builder.
func (_u *ResponseCodeUpdateOne) Mutation() *ResponseCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResponseCodeUpdate builder.
func (_u *ResponseCodeUpdateOne) Where(ps ...predicate.ResponseCode) *ResponseCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResponseCodeUpdateOne) Select(field string, fields ...string) *ResponseCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResponseCode entity.
func (_u *ResponseCodeUpdateOne) Save(ctx context.Context) (*ResponseCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResponseCodeUpdateOne) SaveX(ctx context.Context) *ResponseCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResponseCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResponseCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResponseCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := responsecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ResponseCode.code": %w`, err)}
		}
	}
	return nil
}

func (_u *ResponseCodeUpdateOne) sqlSave(ctx context.Context) (_node *ResponseCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(responsecode.Table, responsecode.Columns, sqlgraph.NewFieldSpec(responsecode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResponseCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, responsecode.FieldID)
		for _, f := range fields {
			if !responsecode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != responsecode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(responsecode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPStatus(); ok {
		_spec.SetField(responsecode.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(responsecode.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DefaultMessage(); ok {
		_spec.SetField(responsecode.FieldDefaultMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(responsecode.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(responsecode.FieldDescription, field.TypeString)
	}
	_spec.Node.Schema = _u.schemaConfig.ResponseCode
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &ResponseCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{responsecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
