// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/internal"
	"github.com/aaron/sakoo-backend/ent/predicate"
	"github.com/aaron/sakoo-backend/ent/responsecode"
)

// ResponseCodeDelete is the builder for deleting a ResponseCode entity.
type ResponseCodeDelete struct {
	config
	hooks    []Hook
	mutation *ResponseCodeMutation
}

// Where appends a list predicates to the ResponseCodeDelete builder.
func (_d *ResponseCodeDelete) Where(ps ...predicate.ResponseCode) *ResponseCodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ResponseCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResponseCodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ResponseCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(responsecode.Table, sqlgraph.NewFieldSpec(responsecode.FieldID, field.TypeInt))
	_spec.Node.Schema = _d.schemaConfig.ResponseCode
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ResponseCodeDeleteOne is the builder for deleting a single ResponseCode entity.
type ResponseCodeDeleteOne struct {
	_d *ResponseCodeDelete
}

// Where appends a list predicates to the ResponseCodeDelete builder.
func (_d *ResponseCodeDeleteOne) Where(ps ...predicate.ResponseCode) *ResponseCodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ResponseCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{responsecode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResponseCodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
