// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/responsecode"
)

// ResponseCodeCreate is the builder for creating a ResponseCode entity.
type ResponseCodeCreate struct {
	config
	mutation *ResponseCodeMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *ResponseCodeCreate) SetCode(v string) *ResponseCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetHTTPStatus sets the "http_status" field.
func (_c *ResponseCodeCreate) SetHTTPStatus(v int) *ResponseCodeCreate {
	_c.mutation.SetHTTPStatus(v)
	return _c
}

// SetDefaultMessage sets the "default_message" field.
func (_c *ResponseCodeCreate) SetDefaultMessage(v string) *ResponseCodeCreate {
	_c.mutation.SetDefaultMessage(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ResponseCodeCreate) SetDescription(v string) *ResponseCodeCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ResponseCodeCreate) SetNillableDescription(v *string) *ResponseCodeCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// Mutation returns the ResponseCodeMutation object of the builder.
func (_c *ResponseCodeCreate) Mutation() *ResponseCodeMutation {
	return _c.mutation
}

// Save creates the ResponseCode in the database.
func (_c *ResponseCodeCreate) Save(ctx context.Context) (*ResponseCode, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResponseCodeCreate) SaveX(ctx context.Context) *ResponseCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResponseCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResponseCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResponseCodeCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "ResponseCode.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := responsecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ResponseCode.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HTTPStatus(); !ok {
		return &ValidationError{Name: "http_status", err: errors.New(`ent: missing required field "ResponseCode.http_status"`)}
	}
	if _, ok := _c.mutation.DefaultMessage(); !ok {
		return &ValidationError{Name: "default_message", err: errors.New(`ent: missing required field "ResponseCode.default_message"`)}
	}
	return nil
}

func (_c *ResponseCodeCreate) sqlSave(ctx context.Context) (*ResponseCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResponseCodeCreate) createSpec() (*ResponseCode, *sqlgraph.CreateSpec) {
	var (
		_node = &ResponseCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(responsecode.Table, sqlgraph.NewFieldSpec(responsecode.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.ResponseCode
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(responsecode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.HTTPStatus(); ok {
		_spec.SetField(responsecode.FieldHTTPStatus, field.TypeInt, value)
		_node.HTTPStatus = value
	}
	if value, ok := _c.mutation.DefaultMessage(); ok {
		_spec.SetField(responsecode.FieldDefaultMessage, field.TypeString, value)
		_node.DefaultMessage = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(responsecode.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	return _node, _spec
}

// ResponseCodeCreateBulk is the builder for creating many ResponseCode entities in bulk.
type ResponseCodeCreateBulk struct {
	config
	err      error
	builders []*ResponseCodeCreate
}

// Save creates the ResponseCode entities in the database.
func (_c *ResponseCodeCreateBulk) Save(ctx context.Context) ([]*ResponseCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResponseCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResponseCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResponseCodeCreateBulk) SaveX(ctx context.Context) []*ResponseCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResponseCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResponseCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
