// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/aaron/sakoo-backend/ent/apilog"
	"github.com/aaron/sakoo-backend/ent/bankaccount"
	"github.com/aaron/sakoo-backend/ent/banner"
	"github.com/aaron/sakoo-backend/ent/comment"
	"github.com/aaron/sakoo-backend/ent/configuration"
	"github.com/aaron/sakoo-backend/ent/currency"
	"github.com/aaron/sakoo-backend/ent/documenttype"
	"github.com/aaron/sakoo-backend/ent/exchangerate"
	"github.com/aaron/sakoo-backend/ent/message"
	"github.com/aaron/sakoo-backend/ent/notification"
	"github.com/aaron/sakoo-backend/ent/paymentcommitment"
	"github.com/aaron/sakoo-backend/ent/paymentnotification"
	"github.com/aaron/sakoo-backend/ent/responsecode"
	"github.com/aaron/sakoo-backend/ent/schema"
	"github.com/aaron/sakoo-backend/ent/thirdpartyaccount"
	"github.com/aaron/sakoo-backend/ent/user"
	"github.com/aaron/sakoo-backend/ent/userdevicetoken"
	"github.com/aaron/sakoo-backend/ent/userotp"
	"github.com/aaron/sakoo-backend/ent/userpasswordhistory"
	"github.com/aaron/sakoo-backend/ent/usersession"
	"github.com/aaron/sakoo-backend/ent/usertype"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apilogFields := schema.ApiLog{}.Fields()
	_ = apilogFields
	// apilogDescTrackCode is the schema descriptor for track_code field.
	apilogDescTrackCode := apilogFields[0].Descriptor()
	// apilog.TrackCodeValidator is a validator for the "track_code" field. It is called by the builders before save.
	apilog.TrackCodeValidator = apilogDescTrackCode.Validators[0].(func(string) error)
	// apilogDescMethod is the schema descriptor for method field.
	apilogDescMethod := apilogFields[2].Descriptor()
	// apilog.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	apilog.MethodValidator = apilogDescMethod.Validators[0].(func(string) error)
	// apilogDescPath is the schema descriptor for path field.
	apilogDescPath := apilogFields[3].Descriptor()
	// apilog.PathValidator is a validator for the "path" field. It is called by the builders before save.
	apilog.PathValidator = apilogDescPath.Validators[0].(func(string) error)
	// apilogDescResponseCode is the schema descriptor for response_code field.
	apilogDescResponseCode := apilogFields[5].Descriptor()
	// apilog.ResponseCodeValidator is a validator for the "response_code" field. It is called by the builders before save.
	apilog.ResponseCodeValidator = apilogDescResponseCode.Validators[0].(func(string) error)
	// apilogDescCreatedAt is the schema descriptor for created_at field.
	apilogDescCreatedAt := apilogFields[7].Descriptor()
	// apilog.DefaultCreatedAt holds the default value on creation for the created_at field.
	apilog.DefaultCreatedAt = apilogDescCreatedAt.Default.(func() time.Time)
	bankaccountFields := schema.BankAccount{}.Fields()
	_ = bankaccountFields
	// bankaccountDescBankName is the schema descriptor for bank_name field.
	bankaccountDescBankName := bankaccountFields[1].Descriptor()
	// bankaccount.BankNameValidator is a validator for the "bank_name" field. It is called by the builders before save.
	bankaccount.BankNameValidator = bankaccountDescBankName.Validators[0].(func(string) error)
	// bankaccountDescAccountNumber is the schema descriptor for account_number field.
	bankaccountDescAccountNumber := bankaccountFields[2].Descriptor()
	// bankaccount.AccountNumberValidator is a validator for the "account_number" field. It is called by the builders before save.
	bankaccount.AccountNumberValidator = bankaccountDescAccountNumber.Validators[0].(func(string) error)
	// bankaccountDescAccountType is the schema descriptor for account_type field.
	bankaccountDescAccountType := bankaccountFields[3].Descriptor()
	// bankaccount.AccountTypeValidator is a validator for the "account_type" field. It is called by the builders before save.
	bankaccount.AccountTypeValidator = bankaccountDescAccountType.Validators[0].(func(string) error)
	// bankaccountDescHolderName is the schema descriptor for holder_name field.
	bankaccountDescHolderName := bankaccountFields[4].Descriptor()
	// bankaccount.HolderNameValidator is a validator for the "holder_name" field. It is called by the builders before save.
	bankaccount.HolderNameValidator = bankaccountDescHolderName.Validators[0].(func(string) error)
	// bankaccountDescCreatedAt is the schema descriptor for created_at field.
	bankaccountDescCreatedAt := bankaccountFields[5].Descriptor()
	// bankaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	bankaccount.DefaultCreatedAt = bankaccountDescCreatedAt.Default.(func() time.Time)
	// bankaccountDescUpdatedAt is the schema descriptor for updated_at field.
	bankaccountDescUpdatedAt := bankaccountFields[6].Descriptor()
	// bankaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bankaccount.DefaultUpdatedAt = bankaccountDescUpdatedAt.Default.(func() time.Time)
	// bankaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bankaccount.UpdateDefaultUpdatedAt = bankaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	bannerFields := schema.Banner{}.Fields()
	_ = bannerFields
	// bannerDescImageURL is the schema descriptor for image_url field.
	bannerDescImageURL := bannerFields[0].Descriptor()
	// banner.ImageURLValidator is a validator for the "image_url" field. It is called by the builders before save.
	banner.ImageURLValidator = bannerDescImageURL.Validators[0].(func(string) error)
	// bannerDescLink is the schema descriptor for link field.
	bannerDescLink := bannerFields[1].Descriptor()
	// banner.LinkValidator is a validator for the "link" field. It is called by the builders before save.
	banner.LinkValidator = bannerDescLink.Validators[0].(func(string) error)
	// bannerDescIsActive is the schema descriptor for is_active field.
	bannerDescIsActive := bannerFields[2].Descriptor()
	// banner.DefaultIsActive holds the default value on creation for the is_active field.
	banner.DefaultIsActive = bannerDescIsActive.Default.(bool)
	// bannerDescDisplayOrder is the schema descriptor for display_order field.
	bannerDescDisplayOrder := bannerFields[3].Descriptor()
	// banner.DefaultDisplayOrder holds the default value on creation for the display_order field.
	banner.DefaultDisplayOrder = bannerDescDisplayOrder.Default.(int)
	// bannerDescCreatedAt is the schema descriptor for created_at field.
	bannerDescCreatedAt := bannerFields[4].Descriptor()
	// banner.DefaultCreatedAt holds the default value on creation for the created_at field.
	banner.DefaultCreatedAt = bannerDescCreatedAt.Default.(func() time.Time)
	// bannerDescUpdatedAt is the schema descriptor for updated_at field.
	bannerDescUpdatedAt := bannerFields[5].Descriptor()
	// banner.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	banner.DefaultUpdatedAt = bannerDescUpdatedAt.Default.(func() time.Time)
	// banner.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	banner.UpdateDefaultUpdatedAt = bannerDescUpdatedAt.UpdateDefault.(func() time.Time)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[3].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	configurationFields := schema.Configuration{}.Fields()
	_ = configurationFields
	// configurationDescKey is the schema descriptor for key field.
	configurationDescKey := configurationFields[0].Descriptor()
	// configuration.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	configuration.KeyValidator = configurationDescKey.Validators[0].(func(string) error)
	// configurationDescCreatedAt is the schema descriptor for created_at field.
	configurationDescCreatedAt := configurationFields[2].Descriptor()
	// configuration.DefaultCreatedAt holds the default value on creation for the created_at field.
	configuration.DefaultCreatedAt = configurationDescCreatedAt.Default.(func() time.Time)
	// configurationDescUpdatedAt is the schema descriptor for updated_at field.
	configurationDescUpdatedAt := configurationFields[3].Descriptor()
	// configuration.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	configuration.DefaultUpdatedAt = configurationDescUpdatedAt.Default.(func() time.Time)
	// configuration.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	configuration.UpdateDefaultUpdatedAt = configurationDescUpdatedAt.UpdateDefault.(func() time.Time)
	currencyFields := schema.Currency{}.Fields()
	_ = currencyFields
	// currencyDescCode is the schema descriptor for code field.
	currencyDescCode := currencyFields[0].Descriptor()
	// currency.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	currency.CodeValidator = currencyDescCode.Validators[0].(func(string) error)
	// currencyDescName is the schema descriptor for name field.
	currencyDescName := currencyFields[1].Descriptor()
	// currency.NameValidator is a validator for the "name" field. It is called by the builders before save.
	currency.NameValidator = currencyDescName.Validators[0].(func(string) error)
	// currencyDescCreatedAt is the schema descriptor for created_at field.
	currencyDescCreatedAt := currencyFields[2].Descriptor()
	// currency.DefaultCreatedAt holds the default value on creation for the created_at field.
	currency.DefaultCreatedAt = currencyDescCreatedAt.Default.(func() time.Time)
	// currencyDescUpdatedAt is the schema descriptor for updated_at field.
	currencyDescUpdatedAt := currencyFields[3].Descriptor()
	// currency.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	currency.DefaultUpdatedAt = currencyDescUpdatedAt.Default.(func() time.Time)
	// currency.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	currency.UpdateDefaultUpdatedAt = currencyDescUpdatedAt.UpdateDefault.(func() time.Time)
	documenttypeFields := schema.DocumentType{}.Fields()
	_ = documenttypeFields
	// documenttypeDescCode is the schema descriptor for code field.
	documenttypeDescCode := documenttypeFields[0].Descriptor()
	// documenttype.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	documenttype.CodeValidator = documenttypeDescCode.Validators[0].(func(string) error)
	// documenttypeDescName is the schema descriptor for name field.
	documenttypeDescName := documenttypeFields[1].Descriptor()
	// documenttype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	documenttype.NameValidator = documenttypeDescName.Validators[0].(func(string) error)
	// documenttypeDescCreatedAt is the schema descriptor for created_at field.
	documenttypeDescCreatedAt := documenttypeFields[2].Descriptor()
	// documenttype.DefaultCreatedAt holds the default value on creation for the created_at field.
	documenttype.DefaultCreatedAt = documenttypeDescCreatedAt.Default.(func() time.Time)
	exchangerateFields := schema.ExchangeRate{}.Fields()
	_ = exchangerateFields
	// exchangerateDescCreatedAt is the schema descriptor for created_at field.
	exchangerateDescCreatedAt := exchangerateFields[6].Descriptor()
	// exchangerate.DefaultCreatedAt holds the default value on creation for the created_at field.
	exchangerate.DefaultCreatedAt = exchangerateDescCreatedAt.Default.(func() time.Time)
	// exchangerateDescUpdatedAt is the schema descriptor for updated_at field.
	exchangerateDescUpdatedAt := exchangerateFields[7].Descriptor()
	// exchangerate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exchangerate.DefaultUpdatedAt = exchangerateDescUpdatedAt.Default.(func() time.Time)
	// exchangerate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exchangerate.UpdateDefaultUpdatedAt = exchangerateDescUpdatedAt.UpdateDefault.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[4].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescTitle is the schema descriptor for title field.
	notificationDescTitle := notificationFields[1].Descriptor()
	// notification.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	notification.TitleValidator = notificationDescTitle.Validators[0].(func(string) error)
	// notificationDescIsRead is the schema descriptor for is_read field.
	notificationDescIsRead := notificationFields[3].Descriptor()
	// notification.DefaultIsRead holds the default value on creation for the is_read field.
	notification.DefaultIsRead = notificationDescIsRead.Default.(bool)
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationFields[5].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	paymentcommitmentFields := schema.PaymentCommitment{}.Fields()
	_ = paymentcommitmentFields
	// paymentcommitmentDescStatus is the schema descriptor for status field.
	paymentcommitmentDescStatus := paymentcommitmentFields[4].Descriptor()
	// paymentcommitment.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	paymentcommitment.StatusValidator = paymentcommitmentDescStatus.Validators[0].(func(string) error)
	// paymentcommitmentDescCreatedAt is the schema descriptor for created_at field.
	paymentcommitmentDescCreatedAt := paymentcommitmentFields[5].Descriptor()
	// paymentcommitment.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentcommitment.DefaultCreatedAt = paymentcommitmentDescCreatedAt.Default.(func() time.Time)
	paymentnotificationFields := schema.PaymentNotification{}.Fields()
	_ = paymentnotificationFields
	// paymentnotificationDescTransactionReference is the schema descriptor for transaction_reference field.
	paymentnotificationDescTransactionReference := paymentnotificationFields[2].Descriptor()
	// paymentnotification.TransactionReferenceValidator is a validator for the "transaction_reference" field. It is called by the builders before save.
	paymentnotification.TransactionReferenceValidator = paymentnotificationDescTransactionReference.Validators[0].(func(string) error)
	// paymentnotificationDescNotificationDate is the schema descriptor for notification_date field.
	paymentnotificationDescNotificationDate := paymentnotificationFields[3].Descriptor()
	// paymentnotification.DefaultNotificationDate holds the default value on creation for the notification_date field.
	paymentnotification.DefaultNotificationDate = paymentnotificationDescNotificationDate.Default.(func() time.Time)
	responsecodeFields := schema.ResponseCode{}.Fields()
	_ = responsecodeFields
	// responsecodeDescCode is the schema descriptor for code field.
	responsecodeDescCode := responsecodeFields[0].Descriptor()
	// responsecode.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	responsecode.CodeValidator = responsecodeDescCode.Validators[0].(func(string) error)
	thirdpartyaccountFields := schema.ThirdPartyAccount{}.Fields()
	_ = thirdpartyaccountFields
	// thirdpartyaccountDescBankName is the schema descriptor for bank_name field.
	thirdpartyaccountDescBankName := thirdpartyaccountFields[1].Descriptor()
	// thirdpartyaccount.BankNameValidator is a validator for the "bank_name" field. It is called by the builders before save.
	thirdpartyaccount.BankNameValidator = thirdpartyaccountDescBankName.Validators[0].(func(string) error)
	// thirdpartyaccountDescAccountNumber is the schema descriptor for account_number field.
	thirdpartyaccountDescAccountNumber := thirdpartyaccountFields[2].Descriptor()
	// thirdpartyaccount.AccountNumberValidator is a validator for the "account_number" field. It is called by the builders before save.
	thirdpartyaccount.AccountNumberValidator = thirdpartyaccountDescAccountNumber.Validators[0].(func(string) error)
	// thirdpartyaccountDescAccountType is the schema descriptor for account_type field.
	thirdpartyaccountDescAccountType := thirdpartyaccountFields[3].Descriptor()
	// thirdpartyaccount.AccountTypeValidator is a validator for the "account_type" field. It is called by the builders before save.
	thirdpartyaccount.AccountTypeValidator = thirdpartyaccountDescAccountType.Validators[0].(func(string) error)
	// thirdpartyaccountDescHolderName is the schema descriptor for holder_name field.
	thirdpartyaccountDescHolderName := thirdpartyaccountFields[4].Descriptor()
	// thirdpartyaccount.HolderNameValidator is a validator for the "holder_name" field. It is called by the builders before save.
	thirdpartyaccount.HolderNameValidator = thirdpartyaccountDescHolderName.Validators[0].(func(string) error)
	// thirdpartyaccountDescAlias is the schema descriptor for alias field.
	thirdpartyaccountDescAlias := thirdpartyaccountFields[5].Descriptor()
	// thirdpartyaccount.AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	thirdpartyaccount.AliasValidator = thirdpartyaccountDescAlias.Validators[0].(func(string) error)
	// thirdpartyaccountDescDocumentNumber is the schema descriptor for document_number field.
	thirdpartyaccountDescDocumentNumber := thirdpartyaccountFields[6].Descriptor()
	// thirdpartyaccount.DocumentNumberValidator is a validator for the "document_number" field. It is called by the builders before save.
	thirdpartyaccount.DocumentNumberValidator = thirdpartyaccountDescDocumentNumber.Validators[0].(func(string) error)
	// thirdpartyaccountDescCreatedAt is the schema descriptor for created_at field.
	thirdpartyaccountDescCreatedAt := thirdpartyaccountFields[7].Descriptor()
	// thirdpartyaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	thirdpartyaccount.DefaultCreatedAt = thirdpartyaccountDescCreatedAt.Default.(func() time.Time)
	// thirdpartyaccountDescUpdatedAt is the schema descriptor for updated_at field.
	thirdpartyaccountDescUpdatedAt := thirdpartyaccountFields[8].Descriptor()
	// thirdpartyaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	thirdpartyaccount.DefaultUpdatedAt = thirdpartyaccountDescUpdatedAt.Default.(func() time.Time)
	// thirdpartyaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	thirdpartyaccount.UpdateDefaultUpdatedAt = thirdpartyaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[2].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescMiddleName is the schema descriptor for middle_name field.
	userDescMiddleName := userFields[3].Descriptor()
	// user.MiddleNameValidator is a validator for the "middle_name" field. It is called by the builders before save.
	user.MiddleNameValidator = userDescMiddleName.Validators[0].(func(string) error)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[4].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = userDescLastName.Validators[0].(func(string) error)
	// userDescSecondLastName is the schema descriptor for second_last_name field.
	userDescSecondLastName := userFields[5].Descriptor()
	// user.SecondLastNameValidator is a validator for the "second_last_name" field. It is called by the builders before save.
	user.SecondLastNameValidator = userDescSecondLastName.Validators[0].(func(string) error)
	// userDescAvatarIndex is the schema descriptor for avatar_index field.
	userDescAvatarIndex := userFields[6].Descriptor()
	// user.DefaultAvatarIndex holds the default value on creation for the avatar_index field.
	user.DefaultAvatarIndex = userDescAvatarIndex.Default.(int)
	// userDescDocumentNumber is the schema descriptor for document_number field.
	userDescDocumentNumber := userFields[9].Descriptor()
	// user.DocumentNumberValidator is a validator for the "document_number" field. It is called by the builders before save.
	user.DocumentNumberValidator = userDescDocumentNumber.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[10].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescRegistrationIP is the schema descriptor for registration_ip field.
	userDescRegistrationIP := userFields[11].Descriptor()
	// user.RegistrationIPValidator is a validator for the "registration_ip" field. It is called by the builders before save.
	user.RegistrationIPValidator = userDescRegistrationIP.Validators[0].(func(string) error)
	// userDescCountry is the schema descriptor for country field.
	userDescCountry := userFields[12].Descriptor()
	// user.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	user.CountryValidator = userDescCountry.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[14].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[15].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	userdevicetokenFields := schema.UserDeviceToken{}.Fields()
	_ = userdevicetokenFields
	// userdevicetokenDescPlatform is the schema descriptor for platform field.
	userdevicetokenDescPlatform := userdevicetokenFields[2].Descriptor()
	// userdevicetoken.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	userdevicetoken.PlatformValidator = userdevicetokenDescPlatform.Validators[0].(func(string) error)
	// userdevicetokenDescCreatedAt is the schema descriptor for created_at field.
	userdevicetokenDescCreatedAt := userdevicetokenFields[3].Descriptor()
	// userdevicetoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	userdevicetoken.DefaultCreatedAt = userdevicetokenDescCreatedAt.Default.(func() time.Time)
	// userdevicetokenDescUpdatedAt is the schema descriptor for updated_at field.
	userdevicetokenDescUpdatedAt := userdevicetokenFields[4].Descriptor()
	// userdevicetoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userdevicetoken.DefaultUpdatedAt = userdevicetokenDescUpdatedAt.Default.(func() time.Time)
	// userdevicetoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userdevicetoken.UpdateDefaultUpdatedAt = userdevicetokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	userotpFields := schema.UserOtp{}.Fields()
	_ = userotpFields
	// userotpDescEmail is the schema descriptor for email field.
	userotpDescEmail := userotpFields[0].Descriptor()
	// userotp.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	userotp.EmailValidator = userotpDescEmail.Validators[0].(func(string) error)
	// userotpDescOtpCode is the schema descriptor for otp_code field.
	userotpDescOtpCode := userotpFields[1].Descriptor()
	// userotp.OtpCodeValidator is a validator for the "otp_code" field. It is called by the builders before save.
	userotp.OtpCodeValidator = userotpDescOtpCode.Validators[0].(func(string) error)
	// userotpDescAction is the schema descriptor for action field.
	userotpDescAction := userotpFields[2].Descriptor()
	// userotp.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	userotp.ActionValidator = userotpDescAction.Validators[0].(func(string) error)
	// userotpDescUsed is the schema descriptor for used field.
	userotpDescUsed := userotpFields[4].Descriptor()
	// userotp.DefaultUsed holds the default value on creation for the used field.
	userotp.DefaultUsed = userotpDescUsed.Default.(bool)
	// userotpDescCreatedAt is the schema descriptor for created_at field.
	userotpDescCreatedAt := userotpFields[5].Descriptor()
	// userotp.DefaultCreatedAt holds the default value on creation for the created_at field.
	userotp.DefaultCreatedAt = userotpDescCreatedAt.Default.(func() time.Time)
	userpasswordhistoryFields := schema.UserPasswordHistory{}.Fields()
	_ = userpasswordhistoryFields
	// userpasswordhistoryDescPasswordHash is the schema descriptor for password_hash field.
	userpasswordhistoryDescPasswordHash := userpasswordhistoryFields[1].Descriptor()
	// userpasswordhistory.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	userpasswordhistory.PasswordHashValidator = userpasswordhistoryDescPasswordHash.Validators[0].(func(string) error)
	// userpasswordhistoryDescCreatedAt is the schema descriptor for created_at field.
	userpasswordhistoryDescCreatedAt := userpasswordhistoryFields[2].Descriptor()
	// userpasswordhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	userpasswordhistory.DefaultCreatedAt = userpasswordhistoryDescCreatedAt.Default.(func() time.Time)
	usersessionFields := schema.UserSession{}.Fields()
	_ = usersessionFields
	// usersessionDescToken is the schema descriptor for token field.
	usersessionDescToken := usersessionFields[1].Descriptor()
	// usersession.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	usersession.TokenValidator = usersessionDescToken.Validators[0].(func(string) error)
	// usersessionDescCreatedAt is the schema descriptor for created_at field.
	usersessionDescCreatedAt := usersessionFields[3].Descriptor()
	// usersession.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersession.DefaultCreatedAt = usersessionDescCreatedAt.Default.(func() time.Time)
	usertypeFields := schema.UserType{}.Fields()
	_ = usertypeFields
	// usertypeDescCode is the schema descriptor for code field.
	usertypeDescCode := usertypeFields[0].Descriptor()
	// usertype.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	usertype.CodeValidator = usertypeDescCode.Validators[0].(func(string) error)
	// usertypeDescName is the schema descriptor for name field.
	usertypeDescName := usertypeFields[1].Descriptor()
	// usertype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	usertype.NameValidator = usertypeDescName.Validators[0].(func(string) error)
	// usertypeDescCreatedAt is the schema descriptor for created_at field.
	usertypeDescCreatedAt := usertypeFields[2].Descriptor()
	// usertype.DefaultCreatedAt holds the default value on creation for the created_at field.
	usertype.DefaultCreatedAt = usertypeDescCreatedAt.Default.(func() time.Time)
}
