// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/internal"
	"github.com/aaron/sakoo-backend/ent/predicate"
	"github.com/aaron/sakoo-backend/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *UserUpdate) ClearUsername() *UserUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *UserUpdate) SetFirstName(v string) *UserUpdate {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFirstName(v *string) *UserUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetMiddleName sets the "middle_name" field.
func (_u *UserUpdate) SetMiddleName(v string) *UserUpdate {
	_u.mutation.SetMiddleName(v)
	return _u
}

// SetNillableMiddleName sets the "middle_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableMiddleName(v *string) *UserUpdate {
	if v != nil {
		_u.SetMiddleName(*v)
	}
	return _u
}

// ClearMiddleName clears the value of the "middle_name" field.
func (_u *UserUpdate) ClearMiddleName() *UserUpdate {
	_u.mutation.ClearMiddleName()
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *UserUpdate) SetLastName(v string) *UserUpdate {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastName(v *string) *UserUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetSecondLastName sets the "second_last_name" field.
func (_u *UserUpdate) SetSecondLastName(v string) *UserUpdate {
	_u.mutation.SetSecondLastName(v)
	return _u
}

// SetNillableSecondLastName sets the "second_last_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSecondLastName(v *string) *UserUpdate {
	if v != nil {
		_u.SetSecondLastName(*v)
	}
	return _u
}

// ClearSecondLastName clears the value of the "second_last_name" field.
func (_u *UserUpdate) ClearSecondLastName() *UserUpdate {
	_u.mutation.ClearSecondLastName()
	return _u
}

// SetAvatarIndex sets the "avatar_index" field.
func (_u *UserUpdate) SetAvatarIndex(v int) *UserUpdate {
	_u.mutation.ResetAvatarIndex()
	_u.mutation.SetAvatarIndex(v)
	return _u
}

// SetNillableAvatarIndex sets the "avatar_index" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatarIndex(v *int) *UserUpdate {
	if v != nil {
		_u.SetAvatarIndex(*v)
	}
	return _u
}

// AddAvatarIndex adds value to the "avatar_index" field.
func (_u *UserUpdate) AddAvatarIndex(v int) *UserUpdate {
	_u.mutation.AddAvatarIndex(v)
	return _u
}

// SetUserTypeID sets the "user_type_id" field.
func (_u *UserUpdate) SetUserTypeID(v int64) *UserUpdate {
	_u.mutation.ResetUserTypeID()
	_u.mutation.SetUserTypeID(v)
	return _u
}

// SetNillableUserTypeID sets the "user_type_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserTypeID(v *int64) *UserUpdate {
	if v != nil {
		_u.SetUserTypeID(*v)
	}
	return _u
}

// AddUserTypeID adds value to the "user_type_id" field.
func (_u *UserUpdate) AddUserTypeID(v int64) *UserUpdate {
	_u.mutation.AddUserTypeID(v)
	return _u
}

// SetDocumentTypeID sets the "document_type_id" field.
func (_u *UserUpdate) SetDocumentTypeID(v int64) *UserUpdate {
	_u.mutation.ResetDocumentTypeID()
	_u.mutation.SetDocumentTypeID(v)
	return _u
}

// SetNillableDocumentTypeID sets the "document_type_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDocumentTypeID(v *int64) *UserUpdate {
	if v != nil {
		_u.SetDocumentTypeID(*v)
	}
	return _u
}

// AddDocumentTypeID adds value to the "document_type_id" field.
func (_u *UserUpdate) AddDocumentTypeID(v int64) *UserUpdate {
	_u.mutation.AddDocumentTypeID(v)
	return _u
}

// ClearDocumentTypeID clears the value of the "document_type_id" field.
func (_u *UserUpdate) ClearDocumentTypeID() *UserUpdate {
	_u.mutation.ClearDocumentTypeID()
	return _u
}

// SetDocumentNumber sets the "document_number" field.
func (_u *UserUpdate) SetDocumentNumber(v string) *UserUpdate {
	_u.mutation.SetDocumentNumber(v)
	return _u
}

// SetNillableDocumentNumber sets the "document_number" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDocumentNumber(v *string) *UserUpdate {
	if v != nil {
		_u.SetDocumentNumber(*v)
	}
	return _u
}

// ClearDocumentNumber clears the value of the "document_number" field.
func (_u *UserUpdate) ClearDocumentNumber() *UserUpdate {
	_u.mutation.ClearDocumentNumber()
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetRegistrationIP sets the "registration_ip" field.
func (_u *UserUpdate) SetRegistrationIP(v string) *UserUpdate {
	_u.mutation.SetRegistrationIP(v)
	return _u
}

// SetNillableRegistrationIP sets the "registration_ip" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRegistrationIP(v *string) *UserUpdate {
	if v != nil {
		_u.SetRegistrationIP(*v)
	}
	return _u
}

// ClearRegistrationIP clears the value of the "registration_ip" field.
func (_u *UserUpdate) ClearRegistrationIP() *UserUpdate {
	_u.mutation.ClearRegistrationIP()
	return _u
}

// SetCountry sets the "country" field.
func (_u *UserUpdate) SetCountry(v string) *UserUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCountry(v *string) *UserUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *UserUpdate) ClearCountry() *UserUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserUpdate) SetDeletedAt(v time.Time) *UserUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDeletedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserUpdate) ClearDeletedAt() *UserUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdate) SetCreatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCreatedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstName(); ok {
		if err := user.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "User.first_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MiddleName(); ok {
		if err := user.MiddleNameValidator(v); err != nil {
			return &ValidationError{Name: "middle_name", err: fmt.Errorf(`ent: validator failed for field "User.middle_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastName(); ok {
		if err := user.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`ent: validator failed for field "User.last_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecondLastName(); ok {
		if err := user.SecondLastNameValidator(v); err != nil {
			return &ValidationError{Name: "second_last_name", err: fmt.Errorf(`ent: validator failed for field "User.second_last_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DocumentNumber(); ok {
		if err := user.DocumentNumberValidator(v); err != nil {
			return &ValidationError{Name: "document_number", err: fmt.Errorf(`ent: validator failed for field "User.document_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegistrationIP(); ok {
		if err := user.RegistrationIPValidator(v); err != nil {
			return &ValidationError{Name: "registration_ip", err: fmt.Errorf(`ent: validator failed for field "User.registration_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := user.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "User.country": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(user.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(user.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MiddleName(); ok {
		_spec.SetField(user.FieldMiddleName, field.TypeString, value)
	}
	if _u.mutation.MiddleNameCleared() {
		_spec.ClearField(user.FieldMiddleName, field.TypeString)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(user.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecondLastName(); ok {
		_spec.SetField(user.FieldSecondLastName, field.TypeString, value)
	}
	if _u.mutation.SecondLastNameCleared() {
		_spec.ClearField(user.FieldSecondLastName, field.TypeString)
	}
	if value, ok := _u.mutation.AvatarIndex(); ok {
		_spec.SetField(user.FieldAvatarIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAvatarIndex(); ok {
		_spec.AddField(user.FieldAvatarIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserTypeID(); ok {
		_spec.SetField(user.FieldUserTypeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserTypeID(); ok {
		_spec.AddField(user.FieldUserTypeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DocumentTypeID(); ok {
		_spec.SetField(user.FieldDocumentTypeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDocumentTypeID(); ok {
		_spec.AddField(user.FieldDocumentTypeID, field.TypeInt64, value)
	}
	if _u.mutation.DocumentTypeIDCleared() {
		_spec.ClearField(user.FieldDocumentTypeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DocumentNumber(); ok {
		_spec.SetField(user.FieldDocumentNumber, field.TypeString, value)
	}
	if _u.mutation.DocumentNumberCleared() {
		_spec.ClearField(user.FieldDocumentNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegistrationIP(); ok {
		_spec.SetField(user.FieldRegistrationIP, field.TypeString, value)
	}
	if _u.mutation.RegistrationIPCleared() {
		_spec.ClearField(user.FieldRegistrationIP, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(user.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(user.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(user.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.User
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *UserUpdateOne) ClearUsername() *UserUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *UserUpdateOne) SetFirstName(v string) *UserUpdateOne {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFirstName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetMiddleName sets the "middle_name" field.
func (_u *UserUpdateOne) SetMiddleName(v string) *UserUpdateOne {
	_u.mutation.SetMiddleName(v)
	return _u
}

// SetNillableMiddleName sets the "middle_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableMiddleName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetMiddleName(*v)
	}
	return _u
}

// ClearMiddleName clears the value of the "middle_name" field.
func (_u *UserUpdateOne) ClearMiddleName() *UserUpdateOne {
	_u.mutation.ClearMiddleName()
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *UserUpdateOne) SetLastName(v string) *UserUpdateOne {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetSecondLastName sets the "second_last_name" field.
func (_u *UserUpdateOne) SetSecondLastName(v string) *UserUpdateOne {
	_u.mutation.SetSecondLastName(v)
	return _u
}

// SetNillableSecondLastName sets the "second_last_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSecondLastName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSecondLastName(*v)
	}
	return _u
}

// ClearSecondLastName clears the value of the "second_last_name" field.
func (_u *UserUpdateOne) ClearSecondLastName() *UserUpdateOne {
	_u.mutation.ClearSecondLastName()
	return _u
}

// SetAvatarIndex sets the "avatar_index" field.
func (_u *UserUpdateOne) SetAvatarIndex(v int) *UserUpdateOne {
	_u.mutation.ResetAvatarIndex()
	_u.mutation.SetAvatarIndex(v)
	return _u
}

// SetNillableAvatarIndex sets the "avatar_index" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatarIndex(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetAvatarIndex(*v)
	}
	return _u
}

// AddAvatarIndex adds value to the "avatar_index" field.
func (_u *UserUpdateOne) AddAvatarIndex(v int) *UserUpdateOne {
	_u.mutation.AddAvatarIndex(v)
	return _u
}

// SetUserTypeID sets the "user_type_id" field.
func (_u *UserUpdateOne) SetUserTypeID(v int64) *UserUpdateOne {
	_u.mutation.ResetUserTypeID()
	_u.mutation.SetUserTypeID(v)
	return _u
}

// SetNillableUserTypeID sets the "user_type_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserTypeID(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetUserTypeID(*v)
	}
	return _u
}

// AddUserTypeID adds value to the "user_type_id" field.
func (_u *UserUpdateOne) AddUserTypeID(v int64) *UserUpdateOne {
	_u.mutation.AddUserTypeID(v)
	return _u
}

// SetDocumentTypeID sets the "document_type_id" field.
func (_u *UserUpdateOne) SetDocumentTypeID(v int64) *UserUpdateOne {
	_u.mutation.ResetDocumentTypeID()
	_u.mutation.SetDocumentTypeID(v)
	return _u
}

// SetNillableDocumentTypeID sets the "document_type_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDocumentTypeID(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetDocumentTypeID(*v)
	}
	return _u
}

// AddDocumentTypeID adds value to the "document_type_id" field.
func (_u *UserUpdateOne) AddDocumentTypeID(v int64) *UserUpdateOne {
	_u.mutation.AddDocumentTypeID(v)
	return _u
}

// ClearDocumentTypeID clears the value of the "document_type_id" field.
func (_u *UserUpdateOne) ClearDocumentTypeID() *UserUpdateOne {
	_u.mutation.ClearDocumentTypeID()
	return _u
}

// SetDocumentNumber sets the "document_number" field.
func (_u *UserUpdateOne) SetDocumentNumber(v string) *UserUpdateOne {
	_u.mutation.SetDocumentNumber(v)
	return _u
}

// SetNillableDocumentNumber sets the "document_number" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDocumentNumber(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetDocumentNumber(*v)
	}
	return _u
}

// ClearDocumentNumber clears the value of the "document_number" field.
func (_u *UserUpdateOne) ClearDocumentNumber() *UserUpdateOne {
	_u.mutation.ClearDocumentNumber()
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetRegistrationIP sets the "registration_ip" field.
func (_u *UserUpdateOne) SetRegistrationIP(v string) *UserUpdateOne {
	_u.mutation.SetRegistrationIP(v)
	return _u
}

// SetNillableRegistrationIP sets the "registration_ip" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRegistrationIP(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetRegistrationIP(*v)
	}
	return _u
}

// ClearRegistrationIP clears the value of the "registration_ip" field.
func (_u *UserUpdateOne) ClearRegistrationIP() *UserUpdateOne {
	_u.mutation.ClearRegistrationIP()
	return _u
}

// SetCountry sets the "country" field.
func (_u *UserUpdateOne) SetCountry(v string) *UserUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCountry(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *UserUpdateOne) ClearCountry() *UserUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserUpdateOne) SetDeletedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDeletedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserUpdateOne) ClearDeletedAt() *UserUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdateOne) SetCreatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCreatedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstName(); ok {
		if err := user.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "User.first_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MiddleName(); ok {
		if err := user.MiddleNameValidator(v); err != nil {
			return &ValidationError{Name: "middle_name", err: fmt.Errorf(`ent: validator failed for field "User.middle_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastName(); ok {
		if err := user.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`ent: validator failed for field "User.last_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecondLastName(); ok {
		if err := user.SecondLastNameValidator(v); err != nil {
			return &ValidationError{Name: "second_last_name", err: fmt.Errorf(`ent: validator failed for field "User.second_last_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DocumentNumber(); ok {
		if err := user.DocumentNumberValidator(v); err != nil {
			return &ValidationError{Name: "document_number", err: fmt.Errorf(`ent: validator failed for field "User.document_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegistrationIP(); ok {
		if err := user.RegistrationIPValidator(v); err != nil {
			return &ValidationError{Name: "registration_ip", err: fmt.Errorf(`ent: validator failed for field "User.registration_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := user.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "User.country": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(user.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(user.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MiddleName(); ok {
		_spec.SetField(user.FieldMiddleName, field.TypeString, value)
	}
	if _u.mutation.MiddleNameCleared() {
		_spec.ClearField(user.FieldMiddleName, field.TypeString)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(user.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecondLastName(); ok {
		_spec.SetField(user.FieldSecondLastName, field.TypeString, value)
	}
	if _u.mutation.SecondLastNameCleared() {
		_spec.ClearField(user.FieldSecondLastName, field.TypeString)
	}
	if value, ok := _u.mutation.AvatarIndex(); ok {
		_spec.SetField(user.FieldAvatarIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAvatarIndex(); ok {
		_spec.AddField(user.FieldAvatarIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserTypeID(); ok {
		_spec.SetField(user.FieldUserTypeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserTypeID(); ok {
		_spec.AddField(user.FieldUserTypeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DocumentTypeID(); ok {
		_spec.SetField(user.FieldDocumentTypeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDocumentTypeID(); ok {
		_spec.AddField(user.FieldDocumentTypeID, field.TypeInt64, value)
	}
	if _u.mutation.DocumentTypeIDCleared() {
		_spec.ClearField(user.FieldDocumentTypeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DocumentNumber(); ok {
		_spec.SetField(user.FieldDocumentNumber, field.TypeString, value)
	}
	if _u.mutation.DocumentNumberCleared() {
		_spec.ClearField(user.FieldDocumentNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegistrationIP(); ok {
		_spec.SetField(user.FieldRegistrationIP, field.TypeString, value)
	}
	if _u.mutation.RegistrationIPCleared() {
		_spec.ClearField(user.FieldRegistrationIP, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(user.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(user.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(user.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.User
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
