// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/internal"
	"github.com/aaron/sakoo-backend/ent/predicate"
	"github.com/aaron/sakoo-backend/ent/userdevicetoken"
)

// UserDeviceTokenUpdate is the builder for updating UserDeviceToken entities.
type UserDeviceTokenUpdate struct {
	config
	hooks    []Hook
	mutation *UserDeviceTokenMutation
}

// Where appends a list predicates to the UserDeviceTokenUpdate builder.
func (_u *UserDeviceTokenUpdate) Where(ps ...predicate.UserDeviceToken) *UserDeviceTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserDeviceTokenUpdate) SetUserID(v int64) *UserDeviceTokenUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserDeviceTokenUpdate) SetNillableUserID(v *int64) *UserDeviceTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserDeviceTokenUpdate) AddUserID(v int64) *UserDeviceTokenUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *UserDeviceTokenUpdate) SetToken(v string) *UserDeviceTokenUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *UserDeviceTokenUpdate) SetNillableToken(v *string) *UserDeviceTokenUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UserDeviceTokenUpdate) SetPlatform(v string) *UserDeviceTokenUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UserDeviceTokenUpdate) SetNillablePlatform(v *string) *UserDeviceTokenUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserDeviceTokenUpdate) SetCreatedAt(v time.Time) *UserDeviceTokenUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserDeviceTokenUpdate) SetNillableCreatedAt(v *time.Time) *UserDeviceTokenUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserDeviceTokenUpdate) SetUpdatedAt(v time.Time) *UserDeviceTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserDeviceTokenMutation object of the builder.
func (_u *UserDeviceTokenUpdate) Mutation() *UserDeviceTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserDeviceTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserDeviceTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserDeviceTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserDeviceTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserDeviceTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userdevicetoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserDeviceTokenUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := userdevicetoken.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UserDeviceToken.platform": %w`, err)}
		}
	}
	return nil
}

func (_u *UserDeviceTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userdevicetoken.Table, userdevicetoken.Columns, sqlgraph.NewFieldSpec(userdevicetoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userdevicetoken.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userdevicetoken.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(userdevicetoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(userdevicetoken.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userdevicetoken.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userdevicetoken.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.UserDeviceToken
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdevicetoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserDeviceTokenUpdateOne is the builder for updating a single UserDeviceToken entity.
type UserDeviceTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserDeviceTokenMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserDeviceTokenUpdateOne) SetUserID(v int64) *UserDeviceTokenUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserDeviceTokenUpdateOne) SetNillableUserID(v *int64) *UserDeviceTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserDeviceTokenUpdateOne) AddUserID(v int64) *UserDeviceTokenUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *UserDeviceTokenUpdateOne) SetToken(v string) *UserDeviceTokenUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *UserDeviceTokenUpdateOne) SetNillableToken(v *string) *UserDeviceTokenUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UserDeviceTokenUpdateOne) SetPlatform(v string) *UserDeviceTokenUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UserDeviceTokenUpdateOne) SetNillablePlatform(v *string) *UserDeviceTokenUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserDeviceTokenUpdateOne) SetCreatedAt(v time.Time) *UserDeviceTokenUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserDeviceTokenUpdateOne) SetNillableCreatedAt(v *time.Time) *UserDeviceTokenUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserDeviceTokenUpdateOne) SetUpdatedAt(v time.Time) *UserDeviceTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserDeviceTokenMutation object of the builder.
func (_u *UserDeviceTokenUpdateOne) Mutation() *UserDeviceTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserDeviceTokenUpdate builder.
func (_u *UserDeviceTokenUpdateOne) Where(ps ...predicate.UserDeviceToken) *UserDeviceTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserDeviceTokenUpdateOne) Select(field string, fields ...string) *UserDeviceTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserDeviceToken entity.
func (_u *UserDeviceTokenUpdateOne) Save(ctx context.Context) (*UserDeviceToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserDeviceTokenUpdateOne) SaveX(ctx context.Context) *UserDeviceToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserDeviceTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserDeviceTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserDeviceTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userdevicetoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserDeviceTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := userdevicetoken.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UserDeviceToken.platform": %w`, err)}
		}
	}
	return nil
}

func (_u *UserDeviceTokenUpdateOne) sqlSave(ctx context.Context) (_node *UserDeviceToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userdevicetoken.Table, userdevicetoken.Columns, sqlgraph.NewFieldSpec(userdevicetoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserDeviceToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userdevicetoken.FieldID)
		for _, f := range fields {
			if !userdevicetoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userdevicetoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userdevicetoken.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userdevicetoken.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(userdevicetoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(userdevicetoken.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userdevicetoken.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userdevicetoken.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.UserDeviceToken
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &UserDeviceToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdevicetoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
