// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aaron/sakoo-backend/ent/internal"
	"github.com/aaron/sakoo-backend/ent/predicate"
	"github.com/aaron/sakoo-backend/ent/userotp"
)

// UserOtpUpdate is the builder for updating UserOtp entities.
type UserOtpUpdate struct {
	config
	hooks    []Hook
	mutation *UserOtpMutation
}

// Where appends a list predicates to the UserOtpUpdate builder.
func (_u *UserOtpUpdate) Where(ps ...predicate.UserOtp) *UserOtpUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserOtpUpdate) SetEmail(v string) *UserOtpUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserOtpUpdate) SetNillableEmail(v *string) *UserOtpUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetOtpCode sets the "otp_code" field.
func (_u *UserOtpUpdate) SetOtpCode(v string) *UserOtpUpdate {
	_u.mutation.SetOtpCode(v)
	return _u
}

// SetNillableOtpCode sets the "otp_code" field if the given value is not nil.
func (_u *UserOtpUpdate) SetNillableOtpCode(v *string) *UserOtpUpdate {
	if v != nil {
		_u.SetOtpCode(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *UserOtpUpdate) SetAction(v string) *UserOtpUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *UserOtpUpdate) SetNillableAction(v *string) *UserOtpUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserOtpUpdate) SetExpiresAt(v time.Time) *UserOtpUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserOtpUpdate) SetNillableExpiresAt(v *time.Time) *UserOtpUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsed sets the "used" field.
func (_u *UserOtpUpdate) SetUsed(v bool) *UserOtpUpdate {
	_u.mutation.SetUsed(v)
	return _u
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_u *UserOtpUpdate) SetNillableUsed(v *bool) *UserOtpUpdate {
	if v != nil {
		_u.SetUsed(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserOtpUpdate) SetCreatedAt(v time.Time) *UserOtpUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserOtpUpdate) SetNillableCreatedAt(v *time.Time) *UserOtpUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the UserOtpMutation object of the builder.
func (_u *UserOtpUpdate) Mutation() *UserOtpMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserOtpUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserOtpUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserOtpUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserOtpUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserOtpUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := userotp.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UserOtp.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OtpCode(); ok {
		if err := userotp.OtpCodeValidator(v); err != nil {
			return &ValidationError{Name: "otp_code", err: fmt.Errorf(`ent: validator failed for field "UserOtp.otp_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := userotp.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "UserOtp.action": %w`, err)}
		}
	}
	return nil
}

func (_u *UserOtpUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userotp.Table, userotp.Columns, sqlgraph.NewFieldSpec(userotp.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(userotp.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.OtpCode(); ok {
		_spec.SetField(userotp.FieldOtpCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(userotp.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userotp.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Used(); ok {
		_spec.SetField(userotp.FieldUsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userotp.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.UserOtp
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userotp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserOtpUpdateOne is the builder for updating a single UserOtp entity.
type UserOtpUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserOtpMutation
}

// SetEmail sets the "email" field.
func (_u *UserOtpUpdateOne) SetEmail(v string) *UserOtpUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserOtpUpdateOne) SetNillableEmail(v *string) *UserOtpUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetOtpCode sets the "otp_code" field.
func (_u *UserOtpUpdateOne) SetOtpCode(v string) *UserOtpUpdateOne {
	_u.mutation.SetOtpCode(v)
	return _u
}

// SetNillableOtpCode sets the "otp_code" field if the given value is not nil.
func (_u *UserOtpUpdateOne) SetNillableOtpCode(v *string) *UserOtpUpdateOne {
	if v != nil {
		_u.SetOtpCode(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *UserOtpUpdateOne) SetAction(v string) *UserOtpUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *UserOtpUpdateOne) SetNillableAction(v *string) *UserOtpUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserOtpUpdateOne) SetExpiresAt(v time.Time) *UserOtpUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserOtpUpdateOne) SetNillableExpiresAt(v *time.Time) *UserOtpUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsed sets the "used" field.
func (_u *UserOtpUpdateOne) SetUsed(v bool) *UserOtpUpdateOne {
	_u.mutation.SetUsed(v)
	return _u
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_u *UserOtpUpdateOne) SetNillableUsed(v *bool) *UserOtpUpdateOne {
	if v != nil {
		_u.SetUsed(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserOtpUpdateOne) SetCreatedAt(v time.Time) *UserOtpUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserOtpUpdateOne) SetNillableCreatedAt(v *time.Time) *UserOtpUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the UserOtpMutation object of the builder.
func (_u *UserOtpUpdateOne) Mutation() *UserOtpMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserOtpUpdate builder.
func (_u *UserOtpUpdateOne) Where(ps ...predicate.UserOtp) *UserOtpUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserOtpUpdateOne) Select(field string, fields ...string) *UserOtpUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserOtp entity.
func (_u *UserOtpUpdateOne) Save(ctx context.Context) (*UserOtp, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserOtpUpdateOne) SaveX(ctx context.Context) *UserOtp {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserOtpUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserOtpUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserOtpUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := userotp.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UserOtp.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OtpCode(); ok {
		if err := userotp.OtpCodeValidator(v); err != nil {
			return &ValidationError{Name: "otp_code", err: fmt.Errorf(`ent: validator failed for field "UserOtp.otp_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := userotp.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "UserOtp.action": %w`, err)}
		}
	}
	return nil
}

func (_u *UserOtpUpdateOne) sqlSave(ctx context.Context) (_node *UserOtp, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userotp.Table, userotp.Columns, sqlgraph.NewFieldSpec(userotp.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserOtp.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userotp.FieldID)
		for _, f := range fields {
			if !userotp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userotp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(userotp.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.OtpCode(); ok {
		_spec.SetField(userotp.FieldOtpCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(userotp.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userotp.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Used(); ok {
		_spec.SetField(userotp.FieldUsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userotp.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.UserOtp
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &UserOtp{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userotp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
