// Code generated by ent, DO NOT EDIT.

package apilog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the apilog type in the database.
	Label = "api_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTrackCode holds the string denoting the track_code field in the database.
	FieldTrackCode = "track_code"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldHTTPStatus holds the string denoting the http_status field in the database.
	FieldHTTPStatus = "http_status"
	// FieldResponseCode holds the string denoting the response_code field in the database.
	FieldResponseCode = "response_code"
	// FieldLatencyMs holds the string denoting the latency_ms field in the database.
	FieldLatencyMs = "latency_ms"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the apilog in the database.
	Table = "api_logs"
)

// Columns holds all SQL columns for apilog fields.
var Columns = []string{
	FieldID,
	FieldTrackCode,
	FieldUserID,
	FieldMethod,
	FieldPath,
	FieldHTTPStatus,
	FieldResponseCode,
	FieldLatencyMs,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TrackCodeValidator is a validator for the "track_code" field. It is called by the builders before save.
	TrackCodeValidator func(string) error
	// MethodValidator is a validator for the "method" field. It is called by the builders before save.
	MethodValidator func(string) error
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator func(string) error
	// ResponseCodeValidator is a validator for the "response_code" field. It is called by the builders before save.
	ResponseCodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ApiLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTrackCode orders the results by the track_code field.
func ByTrackCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackCode, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByHTTPStatus orders the results by the http_status field.
func ByHTTPStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPStatus, opts...).ToFunc()
}

// ByResponseCode orders the results by the response_code field.
func ByResponseCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseCode, opts...).ToFunc()
}

// ByLatencyMs orders the results by the latency_ms field.
func ByLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatencyMs, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
