// Code generated by ent, DO NOT EDIT.

package apilog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/aaron/sakoo-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLTE(FieldID, id))
}

// TrackCode applies equality check predicate on the "track_code" field. It's identical to TrackCodeEQ.
func TrackCode(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldTrackCode, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldUserID, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldMethod, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldPath, v))
}

// HTTPStatus applies equality check predicate on the "http_status" field. It's identical to HTTPStatusEQ.
func HTTPStatus(v int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldHTTPStatus, v))
}

// ResponseCode applies equality check predicate on the "response_code" field. It's identical to ResponseCodeEQ.
func ResponseCode(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldResponseCode, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldLatencyMs, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldCreatedAt, v))
}

// TrackCodeEQ applies the EQ predicate on the "track_code" field.
func TrackCodeEQ(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldTrackCode, v))
}

// TrackCodeNEQ applies the NEQ predicate on the "track_code" field.
func TrackCodeNEQ(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNEQ(FieldTrackCode, v))
}

// TrackCodeIn applies the In predicate on the "track_code" field.
func TrackCodeIn(vs ...string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIn(FieldTrackCode, vs...))
}

// TrackCodeNotIn applies the NotIn predicate on the "track_code" field.
func TrackCodeNotIn(vs ...string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotIn(FieldTrackCode, vs...))
}

// TrackCodeGT applies the GT predicate on the "track_code" field.
func TrackCodeGT(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGT(FieldTrackCode, v))
}

// TrackCodeGTE applies the GTE predicate on the "track_code" field.
func TrackCodeGTE(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGTE(FieldTrackCode, v))
}

// TrackCodeLT applies the LT predicate on the "track_code" field.
func TrackCodeLT(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLT(FieldTrackCode, v))
}

// TrackCodeLTE applies the LTE predicate on the "track_code" field.
func TrackCodeLTE(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLTE(FieldTrackCode, v))
}

// TrackCodeContains applies the Contains predicate on the "track_code" field.
func TrackCodeContains(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldContains(FieldTrackCode, v))
}

// TrackCodeHasPrefix applies the HasPrefix predicate on the "track_code" field.
func TrackCodeHasPrefix(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldHasPrefix(FieldTrackCode, v))
}

// TrackCodeHasSuffix applies the HasSuffix predicate on the "track_code" field.
func TrackCodeHasSuffix(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldHasSuffix(FieldTrackCode, v))
}

// TrackCodeEqualFold applies the EqualFold predicate on the "track_code" field.
func TrackCodeEqualFold(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEqualFold(FieldTrackCode, v))
}

// TrackCodeContainsFold applies the ContainsFold predicate on the "track_code" field.
func TrackCodeContainsFold(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldContainsFold(FieldTrackCode, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotNull(FieldUserID))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldContainsFold(FieldMethod, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldContainsFold(FieldPath, v))
}

// HTTPStatusEQ applies the EQ predicate on the "http_status" field.
func HTTPStatusEQ(v int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldHTTPStatus, v))
}

// HTTPStatusNEQ applies the NEQ predicate on the "http_status" field.
func HTTPStatusNEQ(v int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNEQ(FieldHTTPStatus, v))
}

// HTTPStatusIn applies the In predicate on the "http_status" field.
func HTTPStatusIn(vs ...int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIn(FieldHTTPStatus, vs...))
}

// HTTPStatusNotIn applies the NotIn predicate on the "http_status" field.
func HTTPStatusNotIn(vs ...int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotIn(FieldHTTPStatus, vs...))
}

// HTTPStatusGT applies the GT predicate on the "http_status" field.
func HTTPStatusGT(v int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGT(FieldHTTPStatus, v))
}

// HTTPStatusGTE applies the GTE predicate on the "http_status" field.
func HTTPStatusGTE(v int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGTE(FieldHTTPStatus, v))
}

// HTTPStatusLT applies the LT predicate on the "http_status" field.
func HTTPStatusLT(v int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLT(FieldHTTPStatus, v))
}

// HTTPStatusLTE applies the LTE predicate on the "http_status" field.
func HTTPStatusLTE(v int) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLTE(FieldHTTPStatus, v))
}

// ResponseCodeEQ applies the EQ predicate on the "response_code" field.
func ResponseCodeEQ(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldResponseCode, v))
}

// ResponseCodeNEQ applies the NEQ predicate on the "response_code" field.
func ResponseCodeNEQ(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNEQ(FieldResponseCode, v))
}

// ResponseCodeIn applies the In predicate on the "response_code" field.
func ResponseCodeIn(vs ...string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIn(FieldResponseCode, vs...))
}

// ResponseCodeNotIn applies the NotIn predicate on the "response_code" field.
func ResponseCodeNotIn(vs ...string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotIn(FieldResponseCode, vs...))
}

// ResponseCodeGT applies the GT predicate on the "response_code" field.
func ResponseCodeGT(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGT(FieldResponseCode, v))
}

// ResponseCodeGTE applies the GTE predicate on the "response_code" field.
func ResponseCodeGTE(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGTE(FieldResponseCode, v))
}

// ResponseCodeLT applies the LT predicate on the "response_code" field.
func ResponseCodeLT(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLT(FieldResponseCode, v))
}

// ResponseCodeLTE applies the LTE predicate on the "response_code" field.
func ResponseCodeLTE(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLTE(FieldResponseCode, v))
}

// ResponseCodeContains applies the Contains predicate on the "response_code" field.
func ResponseCodeContains(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldContains(FieldResponseCode, v))
}

// ResponseCodeHasPrefix applies the HasPrefix predicate on the "response_code" field.
func ResponseCodeHasPrefix(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldHasPrefix(FieldResponseCode, v))
}

// ResponseCodeHasSuffix applies the HasSuffix predicate on the "response_code" field.
func ResponseCodeHasSuffix(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldHasSuffix(FieldResponseCode, v))
}

// ResponseCodeIsNil applies the IsNil predicate on the "response_code" field.
func ResponseCodeIsNil() predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIsNull(FieldResponseCode))
}

// ResponseCodeNotNil applies the NotNil predicate on the "response_code" field.
func ResponseCodeNotNil() predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotNull(FieldResponseCode))
}

// ResponseCodeEqualFold applies the EqualFold predicate on the "response_code" field.
func ResponseCodeEqualFold(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEqualFold(FieldResponseCode, v))
}

// ResponseCodeContainsFold applies the ContainsFold predicate on the "response_code" field.
func ResponseCodeContainsFold(v string) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldContainsFold(FieldResponseCode, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int64) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLTE(FieldLatencyMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ApiLog {
	return predicate.ApiLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ApiLog) predicate.ApiLog {
	return predicate.ApiLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ApiLog) predicate.ApiLog {
	return predicate.ApiLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ApiLog) predicate.ApiLog {
	return predicate.ApiLog(sql.NotPredicates(p))
}
