// Code generated by ent, DO NOT EDIT.

package paymentnotification

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentnotification type in the database.
	Label = "payment_notification"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPaymentCommitmentID holds the string denoting the payment_commitment_id field in the database.
	FieldPaymentCommitmentID = "payment_commitment_id"
	// FieldAmountPaid holds the string denoting the amount_paid field in the database.
	FieldAmountPaid = "amount_paid"
	// FieldTransactionReference holds the string denoting the transaction_reference field in the database.
	FieldTransactionReference = "transaction_reference"
	// FieldNotificationDate holds the string denoting the notification_date field in the database.
	FieldNotificationDate = "notification_date"
	// Table holds the table name of the paymentnotification in the database.
	Table = "payment_notifications"
)

// Columns holds all SQL columns for paymentnotification fields.
var Columns = []string{
	FieldID,
	FieldPaymentCommitmentID,
	FieldAmountPaid,
	FieldTransactionReference,
	FieldNotificationDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TransactionReferenceValidator is a validator for the "transaction_reference" field. It is called by the builders before save.
	TransactionReferenceValidator func(string) error
	// DefaultNotificationDate holds the default value on creation for the "notification_date" field.
	DefaultNotificationDate func() time.Time
)

// OrderOption defines the ordering options for the PaymentNotification queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPaymentCommitmentID orders the results by the payment_commitment_id field.
func ByPaymentCommitmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentCommitmentID, opts...).ToFunc()
}

// ByAmountPaid orders the results by the amount_paid field.
func ByAmountPaid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountPaid, opts...).ToFunc()
}

// ByTransactionReference orders the results by the transaction_reference field.
func ByTransactionReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionReference, opts...).ToFunc()
}

// ByNotificationDate orders the results by the notification_date field.
func ByNotificationDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotificationDate, opts...).ToFunc()
}
