// Code generated by ent, DO NOT EDIT.

package paymentnotification

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/aaron/sakoo-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldID, id))
}

// PaymentCommitmentID applies equality check predicate on the "payment_commitment_id" field. It's identical to PaymentCommitmentIDEQ.
func PaymentCommitmentID(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldPaymentCommitmentID, v))
}

// AmountPaid applies equality check predicate on the "amount_paid" field. It's identical to AmountPaidEQ.
func AmountPaid(v float64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldAmountPaid, v))
}

// TransactionReference applies equality check predicate on the "transaction_reference" field. It's identical to TransactionReferenceEQ.
func TransactionReference(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldTransactionReference, v))
}

// NotificationDate applies equality check predicate on the "notification_date" field. It's identical to NotificationDateEQ.
func NotificationDate(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldNotificationDate, v))
}

// PaymentCommitmentIDEQ applies the EQ predicate on the "payment_commitment_id" field.
func PaymentCommitmentIDEQ(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldPaymentCommitmentID, v))
}

// PaymentCommitmentIDNEQ applies the NEQ predicate on the "payment_commitment_id" field.
func PaymentCommitmentIDNEQ(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldPaymentCommitmentID, v))
}

// PaymentCommitmentIDIn applies the In predicate on the "payment_commitment_id" field.
func PaymentCommitmentIDIn(vs ...int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldPaymentCommitmentID, vs...))
}

// PaymentCommitmentIDNotIn applies the NotIn predicate on the "payment_commitment_id" field.
func PaymentCommitmentIDNotIn(vs ...int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldPaymentCommitmentID, vs...))
}

// PaymentCommitmentIDGT applies the GT predicate on the "payment_commitment_id" field.
func PaymentCommitmentIDGT(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldPaymentCommitmentID, v))
}

// PaymentCommitmentIDGTE applies the GTE predicate on the "payment_commitment_id" field.
func PaymentCommitmentIDGTE(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldPaymentCommitmentID, v))
}

// PaymentCommitmentIDLT applies the LT predicate on the "payment_commitment_id" field.
func PaymentCommitmentIDLT(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldPaymentCommitmentID, v))
}

// PaymentCommitmentIDLTE applies the LTE predicate on the "payment_commitment_id" field.
func PaymentCommitmentIDLTE(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldPaymentCommitmentID, v))
}

// PaymentCommitmentIDIsNil applies the IsNil predicate on the "payment_commitment_id" field.
func PaymentCommitmentIDIsNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIsNull(FieldPaymentCommitmentID))
}

// PaymentCommitmentIDNotNil applies the NotNil predicate on the "payment_commitment_id" field.
func PaymentCommitmentIDNotNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotNull(FieldPaymentCommitmentID))
}

// AmountPaidEQ applies the EQ predicate on the "amount_paid" field.
func AmountPaidEQ(v float64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldAmountPaid, v))
}

// AmountPaidNEQ applies the NEQ predicate on the "amount_paid" field.
func AmountPaidNEQ(v float64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldAmountPaid, v))
}

// AmountPaidIn applies the In predicate on the "amount_paid" field.
func AmountPaidIn(vs ...float64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldAmountPaid, vs...))
}

// AmountPaidNotIn applies the NotIn predicate on the "amount_paid" field.
func AmountPaidNotIn(vs ...float64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldAmountPaid, vs...))
}

// AmountPaidGT applies the GT predicate on the "amount_paid" field.
func AmountPaidGT(v float64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldAmountPaid, v))
}

// AmountPaidGTE applies the GTE predicate on the "amount_paid" field.
func AmountPaidGTE(v float64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldAmountPaid, v))
}

// AmountPaidLT applies the LT predicate on the "amount_paid" field.
func AmountPaidLT(v float64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldAmountPaid, v))
}

// AmountPaidLTE applies the LTE predicate on the "amount_paid" field.
func AmountPaidLTE(v float64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldAmountPaid, v))
}

// TransactionReferenceEQ applies the EQ predicate on the "transaction_reference" field.
func TransactionReferenceEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldTransactionReference, v))
}

// TransactionReferenceNEQ applies the NEQ predicate on the "transaction_reference" field.
func TransactionReferenceNEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldTransactionReference, v))
}

// TransactionReferenceIn applies the In predicate on the "transaction_reference" field.
func TransactionReferenceIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldTransactionReference, vs...))
}

// TransactionReferenceNotIn applies the NotIn predicate on the "transaction_reference" field.
func TransactionReferenceNotIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldTransactionReference, vs...))
}

// TransactionReferenceGT applies the GT predicate on the "transaction_reference" field.
func TransactionReferenceGT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldTransactionReference, v))
}

// TransactionReferenceGTE applies the GTE predicate on the "transaction_reference" field.
func TransactionReferenceGTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldTransactionReference, v))
}

// TransactionReferenceLT applies the LT predicate on the "transaction_reference" field.
func TransactionReferenceLT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldTransactionReference, v))
}

// TransactionReferenceLTE applies the LTE predicate on the "transaction_reference" field.
func TransactionReferenceLTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldTransactionReference, v))
}

// TransactionReferenceContains applies the Contains predicate on the "transaction_reference" field.
func TransactionReferenceContains(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContains(FieldTransactionReference, v))
}

// TransactionReferenceHasPrefix applies the HasPrefix predicate on the "transaction_reference" field.
func TransactionReferenceHasPrefix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasPrefix(FieldTransactionReference, v))
}

// TransactionReferenceHasSuffix applies the HasSuffix predicate on the "transaction_reference" field.
func TransactionReferenceHasSuffix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasSuffix(FieldTransactionReference, v))
}

// TransactionReferenceEqualFold applies the EqualFold predicate on the "transaction_reference" field.
func TransactionReferenceEqualFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEqualFold(FieldTransactionReference, v))
}

// TransactionReferenceContainsFold applies the ContainsFold predicate on the "transaction_reference" field.
func TransactionReferenceContainsFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContainsFold(FieldTransactionReference, v))
}

// NotificationDateEQ applies the EQ predicate on the "notification_date" field.
func NotificationDateEQ(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldNotificationDate, v))
}

// NotificationDateNEQ applies the NEQ predicate on the "notification_date" field.
func NotificationDateNEQ(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldNotificationDate, v))
}

// NotificationDateIn applies the In predicate on the "notification_date" field.
func NotificationDateIn(vs ...time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldNotificationDate, vs...))
}

// NotificationDateNotIn applies the NotIn predicate on the "notification_date" field.
func NotificationDateNotIn(vs ...time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldNotificationDate, vs...))
}

// NotificationDateGT applies the GT predicate on the "notification_date" field.
func NotificationDateGT(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldNotificationDate, v))
}

// NotificationDateGTE applies the GTE predicate on the "notification_date" field.
func NotificationDateGTE(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldNotificationDate, v))
}

// NotificationDateLT applies the LT predicate on the "notification_date" field.
func NotificationDateLT(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldNotificationDate, v))
}

// NotificationDateLTE applies the LTE predicate on the "notification_date" field.
func NotificationDateLTE(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldNotificationDate, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentNotification) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentNotification) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentNotification) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.NotPredicates(p))
}
