// Code generated by ent, DO NOT EDIT.

package responsecode

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the responsecode type in the database.
	Label = "response_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldHTTPStatus holds the string denoting the http_status field in the database.
	FieldHTTPStatus = "http_status"
	// FieldDefaultMessage holds the string denoting the default_message field in the database.
	FieldDefaultMessage = "default_message"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// Table holds the table name of the responsecode in the database.
	Table = "response_codes"
)

// Columns holds all SQL columns for responsecode fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldHTTPStatus,
	FieldDefaultMessage,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
)

// OrderOption defines the ordering options for the ResponseCode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByHTTPStatus orders the results by the http_status field.
func ByHTTPStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPStatus, opts...).ToFunc()
}

// ByDefaultMessage orders the results by the default_message field.
func ByDefaultMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultMessage, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}
